FROM techiaith/marytts

RUN apt-get update \
 && apt-get install -y \
	libpq-dev lame supervisor python python-pip python-dev \
 && pip install --upgrade pip 

ADD marytts-api /opt/marytts-api
ADD marytts-api/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

WORKDIR /opt/marytts-api

RUN pip install -r requirements.txt 

RUN mkdir -p /var/log/gunicorn \
 && touch /var/log/gunicorn/marytts-api.error.log

EXPOSE 8008

CMD ["/usr/bin/supervisord"]

