
#!/usr/bin/env python 
# #encoding: UTF-8 
# PROMPTS = [    
    {"identifier": "sample1", "text": u"GWELWN EFFAITH HYN AR JANE WRTH I'W BYWYD CHWALU"},
    {"identifier": "sample2", "text": u"DOEDD DIM MODD RHOI BWYDYDD MEWN OERGELL NEU REWGELL"},
    {"identifier": "sample3", "text": u"ROEDD YN AMHOSIB DEALL BETH OEDD GRUFF BACH EISIAU"},
    {"identifier": "sample4", "text": u"EFALLAI TAW MYND ATI AR EICH LIWT EICH HUN SYDD RAID"},
    {"identifier": "sample5", "text": u"CAFODD Y CWEST I'W FARWOLAETH EI AIL-AGOR DDOE AR GAIS EI DEULU"},
    {"identifier": "sample6", "text": u"OND MAE RHAI RHWYSTRAU YN EU LLE AR Y PRIF FFYRDD RHWNG HWNGARI AC AWSTRIA"},
    {"identifier": "sample7", "text": u"DWI YN MEDDWL IDDYN NHW RHOI BOB SIAWNS IDDO FE"},
    {"identifier": "sample8", "text": u"ROEDD ENGHREIFFTIAU O AELODAU SENEDDOL YN CAEL EU TARGEDU HEFYD"},
    {"identifier": "sample9", "text": u"YR UNIG LE LLE GALL YR ALBAN ROI TRAFFERTH I NI YW YN Y RHENG FLAEN"},
    {"identifier": "sample10", "text": u"FY MHRIF HOBÏAU YW ACTIO A CHANU MEWN GRWPIAU THEATR YN LLANELLI"},
    {"identifier": "sample11", "text": u"ENNILL FY MEDAL AUR MEWN GOLFF OEDD UCHAFBWYNT FY MYWYD"},
    {"identifier": "sample12", "text": u"EFALLAI COLLI FY MAM-GU A FY NHAD-CU YW'R FFACTOR FWYA"},
    {"identifier": "sample13", "text": u"WRTH DDISGWYL AM FEIC NEWYDD DECHREUODD RWYFO"},
    {"identifier": "sample14", "text": u"FE FWYNHEAIS GLAN-LLYN A LLANGRANNOG FEL EI GILYDD"},
    {"identifier": "sample15", "text": u"MAE EI LAW AR EI BEN-LIN YN CUDDIO TWLL YN EI DRYWSUS"},
    {"identifier": "sample16", "text": u"YR UNIG OPSIWN I DDYN CANOL OED Â PHEN MOEL"},
    {"identifier": "sample17", "text": u"BYDD ANGEN YR UN SGILIAU AR BOB SAFLE OND AR RADDFA UWCH"},
    {"identifier": "sample18", "text": u"AWSTRIA A LWCSEMBWRG CYN GORFOD WYNEBU IWGOSLAFIA YN Y ROWND HONNO"},
    {"identifier": "sample19", "text": u"DYW E DDIM YN AMLWG BETH YW NEU OEDD PWRPAS Y STRWYTHURAU"},
    {"identifier": "sample20", "text": u"MAE CHWARTER ARIAN TRETH SBAEN YN DOD O GATALWNIA"},
    {"identifier": "sample21", "text": u"NAWR Y CWBL SYDD GANDDYN NHW YW TWMPATH O RWBEL"},
    {"identifier": "sample22", "text": u"CAIFF Y GORON EI RHOI GAN ŴYL DDRAMA YR WYDDGRUG"},
    {"identifier": "sample23", "text": u"ER MAI MEWN GERDDI TAI PREIFAT OEDD Y RHAN FWYAF"},
    {"identifier": "sample24", "text": u"ANODD YW DOD O HYD I UNRHYW BETH DA I'W DDWEUD AM FIS CHWEFROR"},
    {"identifier": "sample25", "text": u"CEWCH EICH TRWYTHO MEWN IAITH NEWYDD A FYDD YN CANU YN EICH CLUST"},
    {"identifier": "sample26", "text": u"MAE HYN YN ARWAIN AT ANODDEFGARWCH ANGHEUOL"},
    {"identifier": "sample27", "text": u"FIJI AC URUGUAY YN Y GRŴP MWYAF HERIOL OHONYN NHW I GYD"},
    {"identifier": "sample28", "text": u"ALL NEB DDWEUD WRTHOCH CHI FOD EICH BREUDDWYD YN AMHOSIBL"},
    {"identifier": "sample29", "text": u"MI OEDD TEIMLADAU POBL AR Y PRYD YN AMRWD MEDDAI"},
    {"identifier": "sample30", "text": u"ROEDDEN NI EISIAU EU RHOI I BOBL OEDD YN PERFFORMIO"},
    {"identifier": "sample31", "text": u"FLWYDDYN NESAF FE FYDD YR EISTEDDFOD YN DIGWYDD AR FAES Y SIOE FRENHINOL YN LLANELWEDD"},
    {"identifier": "sample32", "text": u"DAETH WYAU SIOCLED YN BOBLOGAIDD ADEG OES FICTORIA"},
    {"identifier": "sample33", "text": u"OND DYW CRISTNOGION HOYW DAL DDIM YN GALLU PRIODI O FEWN YR EGLWYS"},
    {"identifier": "sample34", "text": u"FE FY CYRCH AR Y DDAU LE YN Y BRIFDDINAS DDOE"},
    {"identifier": "sample35", "text": u"CAFODD NAW AELOD O'R GANG EU CARCHARU GAN FARNWR DDYDD IAU"},
    {"identifier": "sample36", "text": u"TRA EIN BOD NI YN AELODAU O'R UNDEB EWROPEAIDD BYDD Y NAWDD YN PARHAU"},
    {"identifier": "sample37", "text": u"RHOWCH GAEAD AR Y SOSBAN A MUDFERWCH AM TUA HANNER AWR"},
    {"identifier": "sample38", "text": u"Y NOD YW BOD CLEIFION YN GALLU CAEL EU TRIN GAN FWY NA JEST Y MEDDYG TEULU"},
    {"identifier": "sample39", "text": u"MAE PRESENOLDEB HEDDLU ARFOG EISOES I'W GWELD YNG NGŴYL Y GELLI"},
    {"identifier": "sample40", "text": u"MAE UNRHYW LEFYDD SYDD DDIM YN CAEL EU LLENWI YN CAEL EU HAIL-HYSBYSEBU"},
    {"identifier": "sample41", "text": u"MAE HEFYD YN EFFEITHIO AR FY HWYLIAU AC AR FY EGNI"},
    {"identifier": "sample42", "text": u"LLADDON NHW FE PAN OEDD E DAN AMHEUAETH YN UNIG"},
    {"identifier": "sample43", "text": u"COFIWCH DDWEUD OS YW HYN YN MYND YN DDIFLAS"},
    {"identifier": "sample44", "text": u"GALL PÏOD DDOD Â LWC DDA NEU LWC DDRWG YN ÔL RHAI"},
    {"identifier": "sample45", "text": u"MI GAFODD Y GWASANAETH TÂN EI GALW TOC CYN PUMP"},
    {"identifier": "sample46", "text": u"DWI A FY NGHRIW YN RHOI PWYSLAIS ENFAWR AR DDIOGELWCH"},
    {"identifier": "sample47", "text": u"DROS YR HAF DWI AM DDECHRAU GWEITHIO AR SGRIPTIAU EFO BETHAN"},
    {"identifier": "sample48", "text": u"ROEDD Y DIGWYDDIAD AR FFORDD Y GOGLEDD RHWNG BWS A MENYW OEDD YN CERDDED"},
    {"identifier": "sample49", "text": u"FEL BOB BLWYDDYN MAE RHAI YN GOFYN A YW'R ARHOLIADAU SAFON UWCH YN MYND YN HAWS"},
    {"identifier": "sample50", "text": u"HEFYD MAE DIGON O AMRYWIAETH FELLY MAE RHYWBETH AT DDANT PAWB"},
    {"identifier": "sample51", "text": u"OND FALLE MOD I NEWYDD DDISGYN I FY NHRAP FY HUN"},
    {"identifier": "sample52", "text": u"CAFODD PERSON OEDD YN SEFYLL GERLLAW HEFYD EI SAETHU"},
    {"identifier": "sample53", "text": u"SIR DDINBYCH A CHONWY CYN GORFFEN AM Y DIWRNOD YN LLANBERIS YNG NGWYNEDD"},
    {"identifier": "sample54", "text": u"ROEDD DAVID PARRY-JONES HEFYD YN DAD I DDAU O BLANT"},
    {"identifier": "sample55", "text": u"FE FYDD Y GWAITH O ROI WYNEB NEWYDD AR FFORDD YR WYDDGRUG YN DECHRAU DYDD SUL"},
    {"identifier": "sample56", "text": u"Y RHESWM YW'R HINSAWDD ECONOMAIDD A LLAI O DDEFNYDD O'R ADNODD"},
    {"identifier": "sample57", "text": u"CAFODD Y DDAU WYBOD AM EU LLWYDDIANT MEWN DIGWYDDIAD ARBENNIG"},
    {"identifier": "sample58", "text": u"POBOL REIT YN Y FFRYNT YN GWEIDDI SIARAD A MEIC YN EDRYCH YN DDIGALON"},
    {"identifier": "sample59", "text": u"POWYS OEDD YR UNIG FWRDD IECHYD HEB UNRHYW ACHOSION"},
    {"identifier": "sample60", "text": u"TRIGOLION YN ARDAL PONTARDDULAIS YN POENI AM EFFAITH CAU EI BANC LLEOL AR Y DRE"},
    {"identifier": "sample61", "text": u"OND BRECHDANAU BOB TRO I TOMOS AC IFAN"},
    {"identifier": "sample62", "text": u"JAMIE ROBERTS OEDD SEREN Y GÊM HEB OS NAC ONI BAI"},
    {"identifier": "sample63", "text": u"MAE CEFNOGAETH AC ANOGAETH RHIENI HEFYD YN ALLWEDDOL"},
    {"identifier": "sample64", "text": u"Y NOD YN Y PEN DRAW YW CEISIO ENNILL Y BENCAMPWRIAETH"},
    {"identifier": "sample65", "text": u"ROEDD FY NHAD YN RHOI MAGLAU LAWR I DDAL Y CWNINGOD AR Y FFERM"},
    {"identifier": "sample66", "text": u"OND ROEDD EI BROFFWYDOLIAETH AR Y TRYWYDD IAWN"},
    {"identifier": "sample67", "text": u"SAIN GALLU RHOI FE MEWN I EIRIAU I FOD YN ONEST"},
    {"identifier": "sample68", "text": u"EFALLAI NA FYDD Y LLINELLAU FFÔN YN GWEITHIO AM YN HIR ETO"},
    {"identifier": "sample69", "text": u"MAE IEITHWEDD CREFYDD YN DOD YN NATURIOL IAWN I FI"},
    {"identifier": "sample70", "text": u"CAFODD Y GWASANAETHAU BRYS EU GALW RHYW AWR YN ÔL"},
    {"identifier": "sample71", "text": u"OND DIFLANNODD Y DDRAIG GOCH FEL YR ARWYDDLUN BRENHINOL PAN DDAETH OES Y TUDURIAID I BEN"},
    {"identifier": "sample72", "text": u"ROEDD FY MAB YN HOLLOL FOEL PAN GAFODD EI ENI"},
    {"identifier": "sample73", "text": u"ROEDD GAN LUKE GALON O AUR A BYDD PAWB OEDD YN EI GARU YN EI GOLLI YN FAWR"},
    {"identifier": "sample74", "text": u"DOEDDEN NI METHU CREU FERSIWN A OEDD DEBYG I BAPUR NEWYDD AR-LEIN"},
    {"identifier": "sample75", "text": u"FE DARODD Y DYN SAWL GWAITH DRWY FFENEST Y CAR"},
    {"identifier": "sample76", "text": u"CAERDYDD A LLUNDAIN RHWNG NOS SADWRN A NOS LUN"},
    {"identifier": "sample77", "text": u"NID YW SOSIALAETH YN AIR BRWNT NEU AMHERTHNASOL BELLACH"},
    {"identifier": "sample78", "text": u"OND DARN BACH O'R HANES YN UNIG YW'R RHEINY"},
    {"identifier": "sample79", "text": u"Y FLAENORIAETH I BLANT RHWNG TRI A SAITH OED OEDD CAEL MWY O LEFYDD I CHWARAE"},
    {"identifier": "sample80", "text": u"Y BROBLEM FAWR YW BOD LLUNDAIN YN RHY DDRUD"},
    {"identifier": "sample81", "text": u"MAE ANGEN IDDYN NHW HEFYD BROFI LEFEL Y GWAED HYD AT WYTH GWAITH Y DYDD"},
    {"identifier": "sample82", "text": u"MAE SWYDDOGION ARBENIGOL YN RHOI CEFNOGAETH I'W DEULU AR HYN O BRYD"},
    {"identifier": "sample83", "text": u"CAFODD Y FFORDD EI CHAU YN DILYN Y DIGWYDDIAD"},
    {"identifier": "sample84", "text": u"FE DDIGWYDDODD Y DRASIEDI TRA BOD Y TRAETH YN LLAWN O BOBL"},
    {"identifier": "sample85", "text": u"HON WRTH GWRS YW FFACTOR BWYSICAF YM MHOBLOGRWYDD UNRHYW FRAGWR"},
    {"identifier": "sample86", "text": u"MAE HIWMOR YN HELPU CHI I FYND O DDYDD I DDYDD"},
    {"identifier": "sample87", "text": u"TAI HAF YN BERCHEN I SAESON OEDD Y RHAN FWYAF O'R TAI A DARGEDWYD"},
    {"identifier": "sample88", "text": u"UN PETH ARALL YW MYND A DIGON O SIOCLED NEU RYWBETH TEBYG"},
    {"identifier": "sample89", "text": u"DES JAMES BOD GANDDO FEDDWL AGORED AM Y CWEST"},
    {"identifier": "sample90", "text": u"ROEDD HEFYD YN GWISGO TROWSUS GOLAU AR Y PRYD"},
    {"identifier": "sample91", "text": u"Y GRED YW BOD Y BACHGEN AR EI WYLIAU YN YR ARDAL"},
    {"identifier": "sample92", "text": u"FEL RHAN O'R GWAITH BYDD PLATFFORM NEWYDD RHIF WYTH YN AGOR YNG NGORSAF CAERDYDD CANOLOG"},
    {"identifier": "sample93", "text": u"CAFODD FFYRDD EU CAU GER PARC MANWERTHU YN LLANDUDNO OHERWYDD DIFROD I ADEILADAU SIOPAU"},
    {"identifier": "sample94", "text": u"CAFODD EI MERCH WYTH OED ANAFIADAU YN Y DIGWYDDIAD"},
    {"identifier": "sample95", "text": u"CAFODD EI THARO GAN FAN A BU FARW O ANAFIADAU I'W PHEN"},
    {"identifier": "sample96", "text": u"ROEDD YN CAEL EI DDISGRIFIO FEL MUDIAD SECIWLAR AR Y DECHRAU"},
    {"identifier": "sample97", "text": u"Y GRED YW EU BOD AR Y FFORDD LAWR OHERWYDD TYWYDD GARW PAN DDIGWYDDODD Y DDAMWAIN"},
    {"identifier": "sample98", "text": u"FYDD Y GWAHARDDIAD DDIM YN BERTHNASOL I E-SIGARÉTS"},
    {"identifier": "sample99", "text": u"MAE WYTH O BOBOL EISOES YN Y DDALFA AR AMHEUAETH O GEISIO LLOFRUDDIO"},
    {"identifier": "sample100", "text": u"CAFODD HI ALWAD FFÔN ODDI WRTH ROGER DIWRNOD CYN IDDI FARW"},
    {"identifier": "sample101", "text": u"CAFODD Y SAFBWYNT HWNNW EI FEIRNIADU GAN SMITH"},
    {"identifier": "sample102", "text": u"MAE OEDI CYN TRINIAETHAU YN DIFETHA ANSAWDD BYWYD POBL"},
    {"identifier": "sample103", "text": u"AMBELL DDEIGRYN AR ÔL GENEDIGAETH FY MAB A FY MERCH"},
    {"identifier": "sample104", "text": u"ROEDD Y DDAU YN GARIADON AC YN GWEITHIO YN Y SIOP HONNO"},
    {"identifier": "sample105", "text": u"MEWN SEDDI ERAILL FEL CAERFFILI A LLANELLI MI OEDD MWYAFRIF LLAFUR YN LLAI"},
    {"identifier": "sample106", "text": u"MAE PAPUR EFO LLINELLAU YN ACHOSI PROBLEM AC MAE FY NODIADAU I GYD YN HOLLOL LLIWGAR"},
    {"identifier": "sample107", "text": u"DOES DIM NADROEDD YN BYW YN WYLLT YN SELAND NEWYDD"},
    {"identifier": "sample108", "text": u"NID AR LONG YN MYND O BORTHLADD I BORTHLADD OEDD Y SWYDD"},
    {"identifier": "sample109", "text": u"ROEDD Y DREIGIAU DDWY GÔL AR Y BLAEN WRTH DROI AC FELLY YR OEDD HI"},
    {"identifier": "sample110", "text": u"POSIBILIADAU DAMCANIAETHOL YW RHAIN AR HYN O BRYD"},
    {"identifier": "sample111", "text": u"ALUN DAVIES BOD ANGEN EDRYCH ETO AR Y SAFONAU WRTH GREU DEDDF IAITH NEWYDD"},
    {"identifier": "sample112", "text": u"SAESNEG OEDD IAITH YR AELWYD AM NAD OEDD EI MAM YN MEDRU SIARAD YR IAITH"},
    {"identifier": "sample113", "text": u"OND DOEDD DIM PALL AR EGNI AC AWCH Y COCHION"},
    {"identifier": "sample114", "text": u"BUDDUGOLIAETH ARALL I DDIOGELWCH AR ADEG MOR ANODD I LOEGR DRUAN"},
    {"identifier": "sample115", "text": u"Y GOBAITH YW Y BYDD Y CAE NEWYDD YN OSGOI GORFOD GOHIRIO GEMAU OHERWYDD Y TYWYDD"},
    {"identifier": "sample116", "text": u"DADLEUODD PRICE FOD GANDDO HAWL I AMDDIFFYN EI EIDDO"},
    {"identifier": "sample117", "text": u"CAFODD YR HEDDLU EU GALW I GAERHUN GER BANGOR NOS FAWRTH"},
    {"identifier": "sample118", "text": u"CAFODD PEIRIANT ACHUB ARBENNIG HEFYD EI ANFON O GAERNARFON"},
    {"identifier": "sample119", "text": u"A DOEDD Y CANIATÂD HWN DDIM YN CAEL EI ROI YN DDI-GWESTIWN"},
    {"identifier": "sample120", "text": u"FE FETHODD YR AIL BRAWF YN Y MODD GWAETHAF POSIB"},
    {"identifier": "sample121", "text": u"DWI DDIM YN POENI Y BYDD Y SAFON YN GOSTWNG"},
    {"identifier": "sample122", "text": u"ROEDD TRI AELOD O'R CRIW A DAU SWYDDOG AR FWRDD YR HOFRENNYDD AR Y PRYD"},
    {"identifier": "sample123", "text": u"DIOLCH HEFYD I GERALLT PENNANT AM EIN HELPU I NABOD RHAI O'R PLANHIGION"},
    {"identifier": "sample124", "text": u"CAMDRINIAETH GORFFOL AC ESGEULUSTOD OEDD YR ACHOSION GAFODD EU COFNODI FWYAF"},
    {"identifier": "sample125", "text": u"BYDD TRAFODAETH O FEWN Y BLAID NAWR YNG NGOLEUNI BETH DDIGWYDDODD YN Y PANEL"},
    {"identifier": "sample126", "text": u"CAFODD NAW OEDOLYN A PHEDWAR PLENTYN DRINIAETH YN Y PARC AM ANAFIADAU"},
    {"identifier": "sample127", "text": u"SONIODD AM EI RWYSTREDIGAETH WRTH TARO NAW"},
    {"identifier": "sample128", "text": u"COFNODWYD MAI BODDI OEDD ACHOS Y FARWOLAETH"},
    {"identifier": "sample129", "text": u"ATEBWYD FY NGHRI GAN YR EISTEDDFOD AR FFURF Y BARIAU AR Y MAES"},
    {"identifier": "sample130", "text": u"DAETH Y DDAU FYD AT EI GILYDD PAN OEDD TORIAD YN Y GÊM AR Y SABOTH"},
    {"identifier": "sample131", "text": u"AELODAU LLAFUR YW GWEDDILL Y GWEINIDOGION"},
    {"identifier": "sample132", "text": u"ROEDD Y DDWY YN FFRINDIAU GORAU ERS YN BLANT"},
    {"identifier": "sample133", "text": u"BYDD EU MANIFFESTO YN CAEL EI LANSIO YNG NGHAERDYDD DDYDD LLUN"},
    {"identifier": "sample134", "text": u"MAE EU STRAEON NHW YN CAEL EU HADRODD YN YR ARDDANGOSFA HEFYD"},
    {"identifier": "sample135", "text": u"CAFODD NIFER O SWYDDOGION CARCHAR EU LLADD A RHANNAU O'R CARCHARDAI EU DIFRODI"},
    {"identifier": "sample136", "text": u"MAE RHAI ADRODDIADAU YN DWEUD NAD YW'R BWRDD RHEOLI AM FUDDSODDI RHAGOR YN Y SAFLE"},
    {"identifier": "sample137", "text": u"AR HYN O BRYD MAE CLEIFION FOD I GAEL ASESIAD IECHYD MEDDWL O FEWN PEDAIR WYTHNOS"},
    {"identifier": "sample138", "text": u"OND SAESNEG YW IAITH Y MAES YN GENEDLAETHOL"},
    {"identifier": "sample139", "text": u"LLETY A OEDD YN ARBENNIG I DEULUOEDD A OEDD YN DDIGARTREF"},
    {"identifier": "sample140", "text": u"DARGANFOD CORFF DYN MEWN ARDAL GOEDIOG GER TESCO YM MANGOR"},
    {"identifier": "sample141", "text": u"NID YW NIFER Y DORF SYDD YN DOD I WYLIO YN UCHEL"},
    {"identifier": "sample142", "text": u"DAETH CADOEDIAD I RYM DDYDD LLUN YN DILYN TRAFODAETHAU RHWNG YR UNOL DALEITHIAU A RWSIA"},
    {"identifier": "sample143", "text": u"PLENTYN DENZIL AC EILEEN OEDD GWRTHRYCH Y STORI"},
    {"identifier": "sample144", "text": u"PROBLEMAU TRAFFIG O FATH NEWYDD YN YR EISTEDDFOD"},
    {"identifier": "sample145", "text": u"MAE LLE I GREDU EI FOD YN CHWARAE AG INJÂN BETROL PAN GAFODD EI LADD"},
    {"identifier": "sample146", "text": u"ALLAN NHW EISTEDD ROWND Y BWRDD A CHAEL PRYD IAWN"},
    {"identifier": "sample147", "text": u"BARN TRI AR DDIWRNOD I ANNOG POBL I GOFRESTRU I BLEIDLEISIO"},
    {"identifier": "sample148", "text": u"ROEDD Y NAW A FU FARW YN AELODAU O'R GANGIAU BEICIAU MODUR"},
    {"identifier": "sample149", "text": u"MAE MISOEDD YN MYND HEIBIO A DOES DIM SÔN AM MEINIR DRUAN"},
    {"identifier": "sample150", "text": u"FE FYDD CYN-FILWYR O BOB CWR O'R DU YN BRESENNOL"},
    {"identifier": "sample151", "text": u"MAE SWYDDOGION NAWR YN GWEITHIO I ADNABOD Y CORFF"},
    {"identifier": "sample152", "text": u"DYW POBOL DDIM YN FODLON TALU I DDOD I HOL TORTH O FARA NEU RHYWBETH"},
    {"identifier": "sample153", "text": u"ROEDD Y RASYS I GYD YN DECHRAU GER CASTELL CAERNARFON"},
    {"identifier": "sample154", "text": u"OND FE AETHON NI I SELAND NEWYDD A PHERFFORMIO YN DDA"},
    {"identifier": "sample155", "text": u"YR AIL BETH YW EI FOD YN GWISGO TEI BRON I BOBMAN"},
    {"identifier": "sample156", "text": u"CAEATHRO A CHIBYN I ARCHWILIO TU ALLAN I'W TAI"},
    {"identifier": "sample157", "text": u"ROEDD EI BWYSLAIS EF AR YR ANGEN I FOD Â MWY O UCHELGAIS"},
    {"identifier": "sample158", "text": u"ROEDD YN DDIGWYDDIAD OFNADWY I BOBL ORFOD DELIO EFO FO"},
    {"identifier": "sample159", "text": u"OND NID AR CHWARAE BACH Y BYDD Y DU YN GADAEL YR UNDEB EWROPEAIDD"},
    {"identifier": "sample160", "text": u"ROEDD LLOEGR YN RHEOLI POB RHAN O'R CHWARAE AM ADEGAU HIR O'R GÊM"},
    {"identifier": "sample161", "text": u"MAE UNRHYW DDRAENOG SYDD ALLAN YNG NGOLAU DYDD ANGEN HELP"},
    {"identifier": "sample162", "text": u"CAFODD GWEINIDOG DROS DRO EI BENODI AR YR EGLWYS"},
    {"identifier": "sample163", "text": u"ROEDD AMRYWIAETH O NWYDDAU AR GAEL YN Y FARCHNAD"},
    {"identifier": "sample164", "text": u"NI FYDD EI RECORDIAU SYDD HEB GAEL EU TORRI FYTH YN CAEL EU TORRI"},
    {"identifier": "sample165", "text": u"OND CAFODD EI THORRI YN DRI DARN AR Y CREIGIAU"},
    {"identifier": "sample166", "text": u"LLANFAIRPWLL YN ACHOSI TRAFFERTH A MWY AR Y LLIF BYW"},
    {"identifier": "sample167", "text": u"DYW E DDIM YN HOFFI POBL YN DOD I FYW YNG NGHAERDYDD"},
    {"identifier": "sample168", "text": u"MAE ANEURIN DONALD YN UN SYDD Â CHRYN DIPYN O BOTENSIAL"},
    {"identifier": "sample169", "text": u"MAE SAWL GEIRIADUR TERMAU HEFYD I'W CAEL AR-LEIN"},
    {"identifier": "sample170", "text": u"GWAUNCAEGURWEN PAN ROEDD Y DARLLEDWR YN SAITH OED"},
    {"identifier": "sample171", "text": u"BYDD HAWL I BLEIDLEISIO BUM GWAITH YN UNIG TRWY BOB DULL O BLEIDLEISIO"},
    {"identifier": "sample172", "text": u"ROEDD OSIAN YN LICIO ACTIO AC YN PERFFORMIO EFO THEATR FACH LLANGEFNI HEFYD"},
    {"identifier": "sample173", "text": u"MAE E A SAWL FFERMWR YN CEFNOGI AROS YN RHAN O'R UE"},
    {"identifier": "sample174", "text": u"CAFODD EI GARCHARU AM WYTH MIS YN LLYS Y GORON YR WYDDGRUG DDYDD MERCHER"},
    {"identifier": "sample175", "text": u"YN YR EGLWYS MAE DWY GARREG O'R OES RUFEINIG"},
    {"identifier": "sample176", "text": u"Y NOD FYDD CADW LLECHEN LAN A SICRHAU O LEIA PWYNT"},
    {"identifier": "sample177", "text": u"DIM OND AWR SYDD I FYND NES BOD Y CANOLFANNAU PLEIDLEISIO YN CAU"},
    {"identifier": "sample178", "text": u"NI CHAFODD UNRHYW UN ARALL EI ANAFU YN Y DIGWYDDIAD"},
    {"identifier": "sample179", "text": u"CLICIWCH O GWMPAS Y LLUN ISOD ER MWY DARGANFOD MWY"},
    {"identifier": "sample180", "text": u"MAE TIMAU ALLAN YN CERDDED A HOFRENNYDD ACHUB"},
    {"identifier": "sample181", "text": u"DOEDD DIM UN GENNYM NI OEDD YN FFITIO GEORGIA OND NES I DDIM MEDDWL"},
    {"identifier": "sample182", "text": u"DW I HEFYD YN EDRYCH MLAEN I CHWILIO AM DALENT NEWYDD"},
    {"identifier": "sample183", "text": u"MAE MARWOLAETH Y DYN YN CAEL EI THRIN FEL UN NAD OES EGLURHAD YN EI CHYLCH"},
    {"identifier": "sample184", "text": u"DARLLEN YR ERTHYGL YN LLAWN RHYDD I BAWB EI FARN"},
    {"identifier": "sample185", "text": u"ROEDD Y SAMPL RHEOLI YN CAEL EI THRINIAETH FEL Y SAMPL PRAWF"},
    {"identifier": "sample186", "text": u"BYDD HONNO YN Y SINEMÂU YN Y FLWYDDYN NEWYDD"},
    {"identifier": "sample187", "text": u"MAE BOD YN SENSITIF I ANGHENION Y CLAF YN HOLLBWYSIG WRTH DDARPARU GOFAL DEMENTIA"},
    {"identifier": "sample188", "text": u"FE FYDD Y PENTREF YN AGOR YN SWYDDOGOL YM MIS RHAGFYR"},
    {"identifier": "sample189", "text": u"MAEN NHW MEWN GWIRIONEDD YN FATH O GEIDWADAETH"},
    {"identifier": "sample190", "text": u"ER BOD TWF YN Y GAMP MAE HERIAU YN BODOLI"},
    {"identifier": "sample191", "text": u"DOEDD Y PERFFORMIAD YN BELL O FOD YN GLASUR OND Y PETH PWYSICAF OEDD ENNILL"},
    {"identifier": "sample192", "text": u"YN SICR DOEDD HI DDIM YN OLL-BRESENNOL FEL HEDDIW"},
    {"identifier": "sample193", "text": u"OND MAE ANGEN RHEOLI UNRHYW BROFION YN EFFEITHIOL"},
    {"identifier": "sample194", "text": u"FE FYDD GWAITH AR ADEILADWAITH Y PRIF ADEILAD YN DECHRAU O FEWN YR WYTHNOSAU NESAF"},
    {"identifier": "sample195", "text": u"OND MI OEDD HWN YN ARFER BOD YN UN O'R STOC"},
    {"identifier": "sample196", "text": u"UN FFORDD ANNISGWYL Y MAE RHAI YN RHAGWELD DEFNYDD Y MAPIO HYN YW MAES POLISI"},
    {"identifier": "sample197", "text": u"CAIFF Y FIRWS EI DROSGLWYDDO GAN FOSGITOS"},
    {"identifier": "sample198", "text": u"DIGON I ATGOFFA DYN O REFFERENDWM YR ALBAN"},
    {"identifier": "sample199", "text": u"MAE POBOL YN DOD ATA I O HYD I OFYN O BLE CES I HI"},
    {"identifier": "sample200", "text": u"NID DIM OND I LŶN Y MAE CERDD DANT YN PERTHYN"},
    {"identifier": "sample201", "text": u"MAE HEDDLU GWENT YN APELIO AM WYBODAETH YN DILYN LLADRAD ARFOG YNG NGHASNEWYDD"},
    {"identifier": "sample202", "text": u"MARK EVANS A PHLANT A PHOBL IFANC YR ARDAL"},
    {"identifier": "sample203", "text": u"CAFODD AELOD ARALL O'R UN TEULU EI GARCHARU AM HERWGIPIO"},
    {"identifier": "sample204", "text": u"DOEDD Y GRONFA HEB GAEL EI GWAGIO ERS CANRIF"},
    {"identifier": "sample205", "text": u"MAE GANDDI BOBLOGAETH O BRON I HANNER MILIWN"},
    {"identifier": "sample206", "text": u"NID OES MWY O WYBODAETH AM EI HANAFIADAU AR HYN O BRYD"},
    {"identifier": "sample207", "text": u"FE GAFODD AMBELL GEFNOGWR BROFIAD UNIGRYW"},
    {"identifier": "sample208", "text": u"DOEDD HWN DDIM YN BERFFORMIAD CRYF IAWN GANDDO"},
    {"identifier": "sample209", "text": u"CEFAIS FY NGENI A'M MAGU YM MERTHYR TUDFUL"},
    {"identifier": "sample210", "text": u"DIGWYDDIADAU I GOFIO AM HANES GWERSYLL FRONGOCH"},
    {"identifier": "sample211", "text": u"OND MAE BAND-EANG ARAF YN GALLU ACHOSI PROBLEMAU"},
    {"identifier": "sample212", "text": u"CAFODD EI GORFF EI DDARGANFOD YN ARDAL TREFORYS"},
    {"identifier": "sample213", "text": u"CAFODD Y DYN EI ARESTIO GAN YR HEDDLU YN HWNGARI"},
    {"identifier": "sample214", "text": u"HALEN OEDD Y FFORDD ORAU I GADW BWYD RHAG SBWYLIO"},
    {"identifier": "sample215", "text": u"HEFYD YN PERFFORMIO AR Y NOSON FYDD CÔR MEIBION PONTARDDULAIS"},
    {"identifier": "sample216", "text": u"OND NID ADREFNU GWASANAETHAU GOFAL YW'R UNIG AMCAN"},
    {"identifier": "sample217", "text": u"DARLLEN YR ERTHYGL YN LLAWN GWELODD FALWEN AR Y BWRDD"},
    {"identifier": "sample218", "text": u"MAE DEG O AWDURDODAU LLEOL YN Y DE DDWYRAIN YN RHAN O'R FARGEN DDINESIG YN Y DE DDWYRAIN"},
    {"identifier": "sample219", "text": u"OND FEDRAI DDIM MEDDWL AM LOT O AMSEROEDD DANI DI FFRAEO"},
    {"identifier": "sample220", "text": u"OND NID OES GAN BOB UN O'R CYRFF YR UN LEFEL O AWDURDOD"},
    {"identifier": "sample221", "text": u"ROEDD HEFYD YN GRICEDWR A CHWARAEODD DROS SWYDD HENFFORDD"},
    {"identifier": "sample222", "text": u"OND MAE DISGWYL OEDI AR Y GWASANAETH AM RHAI ORIAU"},
    {"identifier": "sample223", "text": u"CODWYD AMHEUON PRIF SWYDDOGION YR ORSEDD YN SYTH"},
    {"identifier": "sample224", "text": u"DOEDDEN NHW CHWAITH DDIM YN FODLON DWEUD BETH OEDD GWERTH Y SUSTEM SAIN"},
    {"identifier": "sample225", "text": u"GALL HYN GODI DEGAU O FILOEDD O BUNNAU BOB BLWYDDYN"},
    {"identifier": "sample226", "text": u"ROEDD YN DDISGYBL CHWECHED DOSBARTH AC YN RHAN O BERERINDOD I SBAEN"},
    {"identifier": "sample227", "text": u"DAETH GWEITHIWR O'R GWESTY O HYD IDDO AR Y LAWNT YR ADEILAD"},
    {"identifier": "sample228", "text": u"CAFODD NIFER O BOBOL DRINIAETH AM BROBLEMAU ANADLU YN DILYN Y GWRTHDARO"},
    {"identifier": "sample229", "text": u"DRO ARALL DECHREUODD REGI AR GWSMERIAID"},
    {"identifier": "sample230", "text": u"CREDIR BOD Y PEDWAR DYN YN DOD O LOEGR"},
    {"identifier": "sample231", "text": u"MAE GANDDO FO RYWBETH I DDWEUD NEU MAE GANDDI HI RYWBETH I DDWEUD"},
    {"identifier": "sample232", "text": u"ALED ROBERTS YN DECHRAU AR Y GWAITH AR UNWAITH"},
    {"identifier": "sample233", "text": u"CAFODD FFENESTRI EU TORRI AR BOB UN O'R CEIR"},
    {"identifier": "sample234", "text": u"OND DOES DIM OEDI YN YR ARDAL AR HYN O BRYD"},
    {"identifier": "sample235", "text": u"BYDD AMGUEDDFA GENEDLAETHOL Y GLANNAU AR GAU"},
]