
#!/usr/bin/env python 
# #encoding: UTF-8 
# PROMPTS = [    
    {"identifier": "sample1", "text": u"DOEDD DIM MODD RHOI BWYDYDD MEWN OERGELL NEU REWGELL"},
    {"identifier": "sample2", "text": u"EFALLAI TAW MYND ATI AR EICH LIWT EICH HUN SYDD RAID"},
    {"identifier": "sample3", "text": u"ROEDD YN AMHOSIB DEALL BETH OEDD GRUFF BACH EISIAU"},
    {"identifier": "sample4", "text": u"CAFODD Y CWEST I'W FARWOLAETH EI AIL-AGOR DDOE AR GAIS EI DEULU"},
    {"identifier": "sample5", "text": u"OND MAE RHAI RHWYSTRAU YN EU LLE AR Y PRIF FFYRDD RHWNG HWNGARI AC AWSTRIA"},
    {"identifier": "sample6", "text": u"DWI YN MEDDWL IDDYN NHW RHOI BOB SIAWNS IDDO FE"},
    {"identifier": "sample7", "text": u"ROEDD ENGHREIFFTIAU O AELODAU SENEDDOL YN CAEL EU TARGEDU HEFYD"},
    {"identifier": "sample8", "text": u"MAE EI LAW AR EI BEN-LIN YN CUDDIO TWLL YN EI DRYWSUS"},
    {"identifier": "sample9", "text": u"YR UNIG OPSIWN I DDYN CANOL OED Â PHEN MOEL"},
    {"identifier": "sample10", "text": u"BYDD ANGEN YR UN SGILIAU AR BOB SAFLE OND AR RADDFA UWCH"},
    {"identifier": "sample11", "text": u"ER MAI MEWN GERDDI TAI PREIFAT OEDD Y RHAN FWYAF"},
    {"identifier": "sample12", "text": u"DYW E DDIM YN AMLWG BETH YW NEU OEDD PWRPAS Y STRWYTHURAU"},
    {"identifier": "sample13", "text": u"ANODD YW DOD O HYD I UNRHYW BETH DA I'W DDWEUD AM FIS CHWEFROR"},
    {"identifier": "sample14", "text": u"CEWCH EICH TRWYTHO MEWN IAITH NEWYDD A FYDD YN CANU YN EICH CLUST"},
    {"identifier": "sample15", "text": u"POWYS OEDD YR UNIG FWRDD IECHYD HEB UNRHYW ACHOSION"},
    {"identifier": "sample16", "text": u"TRA EIN BOD NI YN AELODAU O'R UNDEB EWROPEAIDD BYDD Y NAWDD YN PARHAU"},
    {"identifier": "sample17", "text": u"FLWYDDYN NESAF FE FYDD YR EISTEDDFOD YN DIGWYDD AR FAES Y SIOE FRENHINOL YN LLANELWEDD"},
    {"identifier": "sample18", "text": u"ROEDD FY NHAD YN RHOI MAGLAU LAWR I DDAL Y CWNINGOD AR Y FFERM"},
    {"identifier": "sample19", "text": u"MI OEDD TEIMLADAU POBL AR Y PRYD YN AMRWD MEDDAI"},
    {"identifier": "sample20", "text": u"MI GAFODD Y GWASANAETH TÂN EI GALW TOC CYN PUMP"},
    {"identifier": "sample21", "text": u"MAE HEFYD YN EFFEITHIO AR FY HWYLIAU AC AR FY EGNI"},
    {"identifier": "sample22", "text": u"ROEDDEN NI EISIAU EU RHOI I BOBL OEDD YN PERFFORMIO"},
    {"identifier": "sample23", "text": u"MAE UNRHYW LEFYDD SYDD DDIM YN CAEL EU LLENWI YN CAEL EU HAIL-HYSBYSEBU"},
    {"identifier": "sample24", "text": u"DWI A FY NGHRIW YN RHOI PWYSLAIS ENFAWR AR DDIOGELWCH"},
    {"identifier": "sample25", "text": u"DAETH WYAU SIOCLED YN BOBLOGAIDD ADEG OES FICTORIA"},
    {"identifier": "sample26", "text": u"LLADDON NHW FE PAN OEDD E DAN AMHEUAETH YN UNIG"},
    {"identifier": "sample27", "text": u"COFIWCH DDWEUD OS YW HYN YN MYND YN DDIFLAS"},
    {"identifier": "sample28", "text": u"Y NOD YN Y PEN DRAW YW CEISIO ENNILL Y BENCAMPWRIAETH"},
    {"identifier": "sample29", "text": u"TRIGOLION YN ARDAL PONTARDDULAIS YN POENI AM EFFAITH CAU EI BANC LLEOL AR Y DRE"},
    {"identifier": "sample30", "text": u"FYDD Y GWAHARDDIAD DDIM YN BERTHNASOL I E-SIGARÉTS"},
    {"identifier": "sample31", "text": u"DROS YR HAF DWI AM DDECHRAU GWEITHIO AR SGRIPTIAU EFO BETHAN"},
    {"identifier": "sample32", "text": u"ROEDD Y DIGWYDDIAD AR FFORDD Y GOGLEDD RHWNG BWS A MENYW OEDD YN CERDDED"},
    {"identifier": "sample33", "text": u"Y RHESWM YW'R HINSAWDD ECONOMAIDD A LLAI O DDEFNYDD O'R ADNODD"},
    {"identifier": "sample34", "text": u"FE FY CYRCH AR Y DDAU LE YN Y BRIFDDINAS DDOE"},
    {"identifier": "sample35", "text": u"OND FALLE MOD I NEWYDD DDISGYN I FY NHRAP FY HUN"},
    {"identifier": "sample36", "text": u"CAFODD PERSON OEDD YN SEFYLL GERLLAW HEFYD EI SAETHU"},
    {"identifier": "sample37", "text": u"DOEDDEN NI METHU CREU FERSIWN A OEDD DEBYG I BAPUR NEWYDD AR-LEIN"},
    {"identifier": "sample38", "text": u"HEFYD MAE DIGON O AMRYWIAETH FELLY MAE RHYWBETH AT DDANT PAWB"},
    {"identifier": "sample39", "text": u"CAFODD Y DDAU WYBOD AM EU LLWYDDIANT MEWN DIGWYDDIAD ARBENNIG"},
    {"identifier": "sample40", "text": u"MAE CEFNOGAETH AC ANOGAETH RHIENI HEFYD YN ALLWEDDOL"},
    {"identifier": "sample41", "text": u"SAIN GALLU RHOI FE MEWN I EIRIAU I FOD YN ONEST"},
    {"identifier": "sample42", "text": u"YN ÔL RHAI ADRODDIADAU ROEDD AROGL NWY YN YR ARDAL"},
    {"identifier": "sample43", "text": u"OND ROEDD EI BROFFWYDOLIAETH AR Y TRYWYDD IAWN"},
    {"identifier": "sample44", "text": u"EFALLAI NA FYDD Y LLINELLAU FFÔN YN GWEITHIO AM YN HIR ETO"},
    {"identifier": "sample45", "text": u"CAFODD Y GWASANAETHAU BRYS EU GALW RHYW AWR YN ÔL"},
    {"identifier": "sample46", "text": u"MAE IEITHWEDD CREFYDD YN DOD YN NATURIOL IAWN I FI"},
    {"identifier": "sample47", "text": u"CAFODD Y SAFBWYNT HWNNW EI FEIRNIADU GAN SMITH"},
    {"identifier": "sample48", "text": u"ROEDD YN CAEL EI DDISGRIFIO FEL MUDIAD SECIWLAR AR Y DECHRAU"},
    {"identifier": "sample49", "text": u"ROEDD FY MAB YN HOLLOL FOEL PAN GAFODD EI ENI"},
    {"identifier": "sample50", "text": u"MAE SWYDDOGION ARBENIGOL YN RHOI CEFNOGAETH I'W DEULU AR HYN O BRYD"},
    {"identifier": "sample51", "text": u"FE DARODD Y DYN SAWL GWAITH DRWY FFENEST Y CAR"},
    {"identifier": "sample52", "text": u"MAE LLE I GREDU EI FOD YN CHWARAE AG INJÂN BETROL PAN GAFODD EI LADD"},
    {"identifier": "sample53", "text": u"MAE HIWMOR YN HELPU CHI I FYND O DDYDD I DDYDD"},
    {"identifier": "sample54", "text": u"MAE OEDI CYN TRINIAETHAU YN DIFETHA ANSAWDD BYWYD POBL"},
    {"identifier": "sample55", "text": u"ROEDD Y DREIGIAU DDWY GÔL AR Y BLAEN WRTH DROI AC FELLY YR OEDD HI"},
    {"identifier": "sample56", "text": u"Y GRED YW BOD Y BACHGEN AR EI WYLIAU YN YR ARDAL"},
    {"identifier": "sample57", "text": u"Y BROBLEM FAWR YW BOD LLUNDAIN YN RHY DDRUD"},
    {"identifier": "sample58", "text": u"MAE ANGEN IDDYN NHW HEFYD BROFI LEFEL Y GWAED HYD AT WYTH GWAITH Y DYDD"},
    {"identifier": "sample59", "text": u"CAFODD Y FFORDD EI CHAU YN DILYN Y DIGWYDDIAD"},
    {"identifier": "sample60", "text": u"ROEDD HEFYD YN GWISGO TROWSUS GOLAU AR Y PRYD"},
    {"identifier": "sample61", "text": u"CAFODD FFYRDD EU CAU GER PARC MANWERTHU YN LLANDUDNO OHERWYDD DIFROD I ADEILADAU SIOPAU"},
    {"identifier": "sample62", "text": u"UN PETH ARALL YW MYND A DIGON O SIOCLED NEU RYWBETH TEBYG"},
    {"identifier": "sample63", "text": u"FE DDIGWYDDODD Y DRASIEDI TRA BOD Y TRAETH YN LLAWN O BOBL"},
    {"identifier": "sample64", "text": u"TAI HAF YN BERCHEN I SAESON OEDD Y RHAN FWYAF O'R TAI A DARGEDWYD"},
    {"identifier": "sample65", "text": u"MAE WYTH O BOBOL EISOES YN Y DDALFA AR AMHEUAETH O GEISIO LLOFRUDDIO"},
    {"identifier": "sample66", "text": u"BYDD TRAFODAETH O FEWN Y BLAID NAWR YNG NGOLEUNI BETH DDIGWYDDODD YN Y PANEL"},
    {"identifier": "sample67", "text": u"CAFODD EI MERCH WYTH OED ANAFIADAU YN Y DIGWYDDIAD"},
    {"identifier": "sample68", "text": u"POSIBILIADAU DAMCANIAETHOL YW RHAIN AR HYN O BRYD"},
    {"identifier": "sample69", "text": u"ROEDD Y DDAU YN GARIADON AC YN GWEITHIO YN Y SIOP HONNO"},
    {"identifier": "sample70", "text": u"SAESNEG OEDD IAITH YR AELWYD AM NAD OEDD EI MAM YN MEDRU SIARAD YR IAITH"},
    {"identifier": "sample71", "text": u"DADLEUODD PRICE FOD GANDDO HAWL I AMDDIFFYN EI EIDDO"},
    {"identifier": "sample72", "text": u"ALUN DAVIES BOD ANGEN EDRYCH ETO AR Y SAFONAU WRTH GREU DEDDF IAITH NEWYDD"},
    {"identifier": "sample73", "text": u"DIOLCH HEFYD I GERALLT PENNANT AM EIN HELPU I NABOD RHAI O'R PLANHIGION"},
    {"identifier": "sample74", "text": u"FE FETHODD YR AIL BRAWF YN Y MODD GWAETHAF POSIB"},
    {"identifier": "sample75", "text": u"ALED ROBERTS YN DECHRAU AR Y GWAITH AR UNWAITH"},
    {"identifier": "sample76", "text": u"CAFODD PEIRIANT ACHUB ARBENNIG HEFYD EI ANFON O GAERNARFON"},
    {"identifier": "sample77", "text": u"OND SAESNEG YW IAITH Y MAES YN GENEDLAETHOL"},
    {"identifier": "sample78", "text": u"ER BOD TWF YN Y GAMP MAE HERIAU YN BODOLI"},
    {"identifier": "sample79", "text": u"DYW E DDIM YN HOFFI POBL YN DOD I FYW YNG NGHAERDYDD"},
    {"identifier": "sample80", "text": u"A DOEDD Y CANIATÂD HWN DDIM YN CAEL EI ROI YN DDI-GWESTIWN"},
    {"identifier": "sample81", "text": u"TREBLU GOFAL PLANT AM DDIM I RIENI BLANT RHWNG TRI A PHEDWAR OED"},
    {"identifier": "sample82", "text": u"DWI DDIM YN POENI Y BYDD Y SAFON YN GOSTWNG"},
    {"identifier": "sample83", "text": u"CAFODD NAW OEDOLYN A PHEDWAR PLENTYN DRINIAETH YN Y PARC AM ANAFIADAU"},
    {"identifier": "sample84", "text": u"ROEDD DARNAU O LECHI YN DISGYN UWCH EIN PENNAU NI"},
    {"identifier": "sample85", "text": u"DWI MEWN HWYLIAU REIT DDIFRIFOL YR WYTHNOS HON"},
    {"identifier": "sample86", "text": u"ROEDD OSIAN YN LICIO ACTIO AC YN PERFFORMIO EFO THEATR FACH LLANGEFNI HEFYD"},
    {"identifier": "sample87", "text": u"MAE EU STRAEON NHW YN CAEL EU HADRODD YN YR ARDDANGOSFA HEFYD"},
    {"identifier": "sample88", "text": u"PROBLEMAU TRAFFIG O FATH NEWYDD YN YR EISTEDDFOD"},
    {"identifier": "sample89", "text": u"ATEBWYD FY NGHRI GAN YR EISTEDDFOD AR FFURF Y BARIAU AR Y MAES"},
    {"identifier": "sample90", "text": u"CAFODD AELOD ARALL O'R UN TEULU EI GARCHARU AM HERWGIPIO"},
    {"identifier": "sample91", "text": u"MAE SWYDDOGION NAWR YN GWEITHIO I ADNABOD Y CORFF"},
    {"identifier": "sample92", "text": u"BYDD HAWL I BLEIDLEISIO BUM GWAITH YN UNIG TRWY BOB DULL O BLEIDLEISIO"},
    {"identifier": "sample93", "text": u"DAETH GWEITHIWR O'R GWESTY O HYD IDDO AR Y LAWNT YR ADEILAD"},
    {"identifier": "sample94", "text": u"ALLAN NHW EISTEDD ROWND Y BWRDD A CHAEL PRYD IAWN"},
    {"identifier": "sample95", "text": u"CAFODD NIFER O SWYDDOGION CARCHAR EU LLADD A RHANNAU O'R CARCHARDAI EU DIFRODI"},
    {"identifier": "sample96", "text": u"PLENTYN DENZIL AC EILEEN OEDD GWRTHRYCH Y STORI"},
    {"identifier": "sample97", "text": u"DW I HEFYD YN EDRYCH MLAEN I CHWILIO AM DALENT NEWYDD"},
    {"identifier": "sample98", "text": u"NID YW NIFER Y DORF SYDD YN DOD I WYLIO YN UCHEL"},
    {"identifier": "sample99", "text": u"LLETY A OEDD YN ARBENNIG I DEULUOEDD A OEDD YN DDIGARTREF"},
    {"identifier": "sample100", "text": u"MAE DISGWYL I BRIS GOSOD COFEB HEFYD GODI"},
    {"identifier": "sample101", "text": u"DW I WRTH FY MODD YN CERDDED AC YN HOFF O NATUR"},
    {"identifier": "sample102", "text": u"LLANFAIRPWLL YN ACHOSI TRAFFERTH A MWY AR Y LLIF BYW"},
    {"identifier": "sample103", "text": u"MAE SAWL GEIRIADUR TERMAU HEFYD I'W CAEL AR-LEIN"},
    {"identifier": "sample104", "text": u"YR ARIAN YW'R RHAN AMHERTHNASOL YN HYN I GYD"},
    {"identifier": "sample105", "text": u"MAE BOD YN SENSITIF I ANGHENION Y CLAF YN HOLLBWYSIG WRTH DDARPARU GOFAL DEMENTIA"},
    {"identifier": "sample106", "text": u"OND NID OES GAN BOB UN O'R CYRFF YR UN LEFEL O AWDURDOD"},
    {"identifier": "sample107", "text": u"BYDD Y LLINELL DERFYN GER NEUADD Y DDINAS YNG NGHANOL CAERDYDD"},
    {"identifier": "sample108", "text": u"CAFODD GWEINIDOG DROS DRO EI BENODI AR YR EGLWYS"},
    {"identifier": "sample109", "text": u"HALEN OEDD Y FFORDD ORAU I GADW BWYD RHAG SBWYLIO"},
    {"identifier": "sample110", "text": u"YN ANFFODUS ROEDD RHAID I MI FYND NÔL I AIL-SEFYLL"},
    {"identifier": "sample111", "text": u"BARN TRI AR DDIWRNOD I ANNOG POBL I GOFRESTRU I BLEIDLEISIO"},
    {"identifier": "sample112", "text": u"ROEDD EI BWYSLAIS EF AR YR ANGEN I FOD Â MWY O UCHELGAIS"},
    {"identifier": "sample113", "text": u"Y GWASANAETH IECHYD YW'R PWNC ARALL SYDD YN BWYSIG IDDO"},
    {"identifier": "sample114", "text": u"MAE GANDDO FO RYWBETH I DDWEUD NEU MAE GANDDI HI RYWBETH I DDWEUD"},
    {"identifier": "sample115", "text": u"OND ERS RHYW FLWYDDYN DYW ELUSENNAU MAWR DDIM YN DERBYN GRANTIAU"},
    {"identifier": "sample116", "text": u"UN OEDD YN Y FARCHNAD NOS SADWRN OEDD GARETH"},
    {"identifier": "sample117", "text": u"AC MAE HYN OLL CYN I BOBOL DDECHRAU CANOLBWYNTIO AR YR ETHOLIAD O DDIFRIF"},
    {"identifier": "sample118", "text": u"ROEDD YN DDIGWYDDIAD OFNADWY I BOBL ORFOD DELIO EFO FO"},
    {"identifier": "sample119", "text": u"YR AIL BETH YW EI FOD YN GWISGO TEI BRON I BOBMAN"},
    {"identifier": "sample120", "text": u"DEALLIR Y BYDD Y GRANT YN CAEL EI LEIHAU BOB BLWYDDYN"},
    {"identifier": "sample121", "text": u"ROEDD YN DDISGYBL CHWECHED DOSBARTH AC YN RHAN O BERERINDOD I SBAEN"},
    {"identifier": "sample122", "text": u"GWAUNCAEGURWEN PAN ROEDD Y DARLLEDWR YN SAITH OED"},
    {"identifier": "sample123", "text": u"CAFODD Y RHAN FWYAF O'R CARCHARORION EU LLADD AR UNWAITH MEWN SIAMBR NWY"},
    {"identifier": "sample124", "text": u"NI FYDD EI RECORDIAU SYDD HEB GAEL EU TORRI FYTH YN CAEL EU TORRI"},
    {"identifier": "sample125", "text": u"OND CAFODD EI THORRI YN DRI DARN AR Y CREIGIAU"},
    {"identifier": "sample126", "text": u"UN FFORDD ANNISGWYL Y MAE RHAI YN RHAGWELD DEFNYDD Y MAPIO HYN YW MAES POLISI"},
    {"identifier": "sample127", "text": u"DARLLEN YR ERTHYGL YN LLAWN RHYDD I BAWB EI FARN"},
    {"identifier": "sample128", "text": u"DAETH YR HEDDLU O HYD I GYRFF Y DDAU YN ARDAL LLANABER"},
    {"identifier": "sample129", "text": u"MAE FY CHWIORYDD YN DAL I FYW A GWEITHIO YN LLUNDAIN"},
    {"identifier": "sample130", "text": u"BYDD Y CAIS YN CAEL EI DRAFOD YR WYTHNOS NESAF"},
    {"identifier": "sample131", "text": u"NID OES Y FATH BETH Â PHOBL GELTAIDD YN BODOLI"},
    {"identifier": "sample132", "text": u"Y NOD FYDD CADW LLECHEN LAN A SICRHAU O LEIA PWYNT"},
    {"identifier": "sample133", "text": u"FE FYDD Y GWASANAETH I DDATHLU EI FYWYD YN AMLOSGFA BANGOR"},
    {"identifier": "sample134", "text": u"NI CHAFODD UNRHYW UN ARALL EI ANAFU YN Y DIGWYDDIAD"},
    {"identifier": "sample135", "text": u"CAFODD EI CHORFF EI GLUDO NÔL AT EI THEULU YN CHINA YN DILYN EI MARWOLAETH"},
    {"identifier": "sample136", "text": u"BELLACH HEFYD ROEDD POBL YN GALW HEIBIO EIN CARTREF YN SIOP Y PENTRE"},
    {"identifier": "sample137", "text": u"CAFODD FFENESTRI EU TORRI AR BOB UN O'R CEIR"},
    {"identifier": "sample138", "text": u"DIM OND AWR SYDD I FYND NES BOD Y CANOLFANNAU PLEIDLEISIO YN CAU"},
    {"identifier": "sample139", "text": u"OND DYW PÊL-DROED DDIM YN CAEL EI CHWARAE AR BAPUR"},
    {"identifier": "sample140", "text": u"MAE TIMAU ALLAN YN CERDDED A HOFRENNYDD ACHUB"},
    {"identifier": "sample141", "text": u"ROEDD Y STRYD YNG NGHANOL CAERDYDD AR GAU FORE MERCHER YN DILYN Y DIGWYDDIAD"},
    {"identifier": "sample142", "text": u"MAE GEN I DDATGUDDIAD MAWR I'W RANNU EFO CHI BOBOL"},
    {"identifier": "sample143", "text": u"FE FYDD Y PENTREF YN AGOR YN SWYDDOGOL YM MIS RHAGFYR"},
    {"identifier": "sample144", "text": u"MAEN NHW MEWN GWIRIONEDD YN FATH O GEIDWADAETH"},
    {"identifier": "sample145", "text": u"ROEDD Y SAMPL RHEOLI YN CAEL EI THRINIAETH FEL Y SAMPL PRAWF"},
    {"identifier": "sample146", "text": u"BYDD HONNO YN Y SINEMÂU YN Y FLWYDDYN NEWYDD"},
    {"identifier": "sample147", "text": u"CREDIR BOD Y PEDWAR DYN YN DOD O LOEGR"},
    {"identifier": "sample148", "text": u"DOEDD DIM UN GENNYM NI OEDD YN FFITIO GEORGIA OND NES I DDIM MEDDWL"},
    {"identifier": "sample149", "text": u"GALL HYN ACHOSI TYWYDD GARW A DINISTRIOL O GWMPAS Y BYD"},
    {"identifier": "sample150", "text": u"CAFODD EI GARCHARU AM NAW MIS YN LLYS Y GORON YR WYDDGRUG DDYDD IAU"},
    {"identifier": "sample151", "text": u"DIGON GWIR FOD HYN YN EILBETH I SICRHAU PERFFORMIAD DA AR Y CAE"},
    {"identifier": "sample152", "text": u"MAE POBOL YN DOD ATA I O HYD I OFYN O BLE CES I HI"},
    {"identifier": "sample153", "text": u"ROEDD YN GWISGO SIWMPER OLAU AC YN CARIO BAG DU"},
    {"identifier": "sample154", "text": u"CAFODD HYN EI DDANGOS YN ERBYN YR ALBAN A FFRAINC"},
    {"identifier": "sample155", "text": u"MAE E AR GAEL YN AMLOSGFA LLANELLI AR HYN O BRYD"},
    {"identifier": "sample156", "text": u"DW I DDIM YN GWELD PWRPAS CREU GORMOD O ORNEST YN Y SGRYM"},
    {"identifier": "sample157", "text": u"HANES DAU A DDECHREUODD BENNOD NEWYDD YN EU BYWYD"},
    {"identifier": "sample158", "text": u"MAE HON YN MYND O'R HEN HARBWR AT DROED Y CASTELL"},
    {"identifier": "sample159", "text": u"YN YR EGLWYS MAE DWY GARREG O'R OES RUFEINIG"},
    {"identifier": "sample160", "text": u"DOEDD Y PERFFORMIAD YN BELL O FOD YN GLASUR OND Y PETH PWYSICAF OEDD ENNILL"},
    {"identifier": "sample161", "text": u"MAE UNRHYW DDRAENOG SYDD ALLAN YNG NGOLAU DYDD ANGEN HELP"},
    {"identifier": "sample162", "text": u"YN SICR DOEDD HI DDIM YN OLL-BRESENNOL FEL HEDDIW"},
    {"identifier": "sample163", "text": u"OND DW I DDIM YN GRAC AC YN GWELD BAI AR NEB"},
    {"identifier": "sample164", "text": u"OND MAE ANGEN RHEOLI UNRHYW BROFION YN EFFEITHIOL"},
    {"identifier": "sample165", "text": u"FE FYDD GWAITH AR ADEILADWAITH Y PRIF ADEILAD YN DECHRAU O FEWN YR WYTHNOSAU NESAF"},
    {"identifier": "sample166", "text": u"DWI DI BOD YN LWCUS TU HWNT I ALLU BYW YN FY ARDAL"},
    {"identifier": "sample167", "text": u"CAFODD Y RHEITHGOR EU HANFON ADREF DDYDD GWENER OHERWYDD SALWCH I UN AELOD"},
    {"identifier": "sample168", "text": u"FE GAFODD PEDWAR O BOBL ERAILL EU HANAFU YN Y DIGWYDDIAD"},
    {"identifier": "sample169", "text": u"BYDD BARNWR NAWR YN AILEDRYCH AR YR ACHOS"},
    {"identifier": "sample170", "text": u"MAE GANDDI BOBLOGAETH O BRON I HANNER MILIWN"},
    {"identifier": "sample171", "text": u"ROEDD AMRYWIAETH O NWYDDAU AR GAEL YN Y FARCHNAD"},
    {"identifier": "sample172", "text": u"OND DOES GANDDI DDIM GWRTHWYNEBIAD I NEB ARDDEL UNRHYW GREFYDD"},
    {"identifier": "sample173", "text": u"NID DIM OND I LŶN Y MAE CERDD DANT YN PERTHYN"},
    {"identifier": "sample174", "text": u"BYDD Y CERFLUN YN SEFYLL AR BONT YN EDRYCH ALLAN TUAG AT GASTELL PENFRO"},
    {"identifier": "sample175", "text": u"DOEDDEN NHW CHWAITH DDIM YN FODLON DWEUD BETH OEDD GWERTH Y SUSTEM SAIN"},
    {"identifier": "sample176", "text": u"MARK EVANS A PHLANT A PHOBL IFANC YR ARDAL"},
    {"identifier": "sample177", "text": u"OND MAE BAND-EANG ARAF YN GALLU ACHOSI PROBLEMAU"},
    {"identifier": "sample178", "text": u"ROEDD Y PWLL YN ARFER BOD YN WYRDDLAS TROFANNOL"},
    {"identifier": "sample179", "text": u"FE GAFODD AMBELL GEFNOGWR BROFIAD UNIGRYW"},
    {"identifier": "sample180", "text": u"DOEDD HWN DDIM YN BERFFORMIAD CRYF IAWN GANDDO"},
    {"identifier": "sample181", "text": u"CAFODD EI GORFF EI DDARGANFOD YN ARDAL TREFORYS"},
    {"identifier": "sample182", "text": u"CAFODD Y DYN EI ARESTIO GAN YR HEDDLU YN HWNGARI"},
    {"identifier": "sample183", "text": u"DOEDD DIM CERBYD ARALL YN RHAN O'R DDAMWAIN"},
    {"identifier": "sample184", "text": u"OND NID ADREFNU GWASANAETHAU GOFAL YW'R UNIG AMCAN"},
    {"identifier": "sample185", "text": u"DARLLEN YR ERTHYGL YN LLAWN GWELODD FALWEN AR Y BWRDD"},
    {"identifier": "sample186", "text": u"DIGON I ATGOFFA DYN O REFFERENDWM YR ALBAN"},
    {"identifier": "sample187", "text": u"AETH HWNNA MOR GLOU AC MOR ARAF AR YR UN PRYD"},
    {"identifier": "sample188", "text": u"NES I FYND ATI I DDECHRAU SGWENNU STRAEON"},
    {"identifier": "sample189", "text": u"OND MAE DISGWYL OEDI AR Y GWASANAETH AM RHAI ORIAU"},
    {"identifier": "sample190", "text": u"NID YW'R DIGWYDDIAD YN CAEL EI DRIN FEL UN AMHEUS"},
    {"identifier": "sample191", "text": u"NID OES MWY O WYBODAETH AM Y FARWOLAETH AR HYN O BRYD"},
    {"identifier": "sample192", "text": u"BYDD YR ARIAN HEFYD YN HELPU DARPARU TAI PREIFAT A FFORDDIADWY"},
    {"identifier": "sample193", "text": u"NID YW RHAI ARDALOEDD O LOEGR YN DERBYN YR UN FFOADUR"},
    {"identifier": "sample194", "text": u"CAFODD NIFER O BOBOL DRINIAETH AM BROBLEMAU ANADLU YN DILYN Y GWRTHDARO"},
    {"identifier": "sample195", "text": u"DRO ARALL DECHREUODD REGI AR GWSMERIAID"},
    {"identifier": "sample196", "text": u"NAWR YW'R AMSER IDDYN NHW GADW AT EU GAIR A DECHRAU GWEITHREDU"},
    {"identifier": "sample197", "text": u"OND MI OEDD HWN YN ARFER BOD YN UN O'R STOC"},
    {"identifier": "sample198", "text": u"OND DOES DIM OEDI YN YR ARDAL AR HYN O BRYD"},
    {"identifier": "sample199", "text": u"BYDD YN RHAID I HUGHES GOFRESTRU FEL TROSEDDWR RHYW"},
    {"identifier": "sample200", "text": u"MAE TRI DYN GAFODD EU HARESTIO DDYDD LLUN YN PARHAU YN Y DDALFA"},
    {"identifier": "sample201", "text": u"MAE ADRODDIADAU LLEOL YN DWEUD MAI LLOND BAG O FFRWYDRON GAFODD EI DANIO"},
    {"identifier": "sample202", "text": u"HONNODD NAD OEDD YN GALLU COFIO BETH DDIGWYDDODD AR Y LLWYBR"},
    {"identifier": "sample203", "text": u"DOEDD E DDIM YN MYND I ADAEL I MI FYND YN HAWDD"},
    {"identifier": "sample204", "text": u"CLICIWCH O GWMPAS Y LLUN ISOD ER MWY DARGANFOD MWY"},
    {"identifier": "sample205", "text": u"YN ANAD DIM YR HAWL I ADAEL YW MAEN PRAWF SOFRANIAETH"},
    {"identifier": "sample206", "text": u"BYDD Y MATERION HYN YN EFFEITHIO AR HYD EI DDEDFRYD"},
    {"identifier": "sample207", "text": u"MAE O BELLACH AR LWYBR GWAHANOL IAWN AC YN AIL-ADEILADU EI FYWYD"},
    {"identifier": "sample208", "text": u"CAFODD GWASANAETHAU BRYS EU GALW YN DILYN DAMWAIN DDIFRIFOL AR FFORDD YNG NGHEREDIGION"},
    {"identifier": "sample209", "text": u"MAE HEFYD YN GWEITHIO FEL BARDD A DARLLEDWR LLAWRYDD"},
    {"identifier": "sample210", "text": u"MI FYDD Y BROSES YN DEBYG I ETHOLIADAU ERAILL"},
    {"identifier": "sample211", "text": u"DOEDD FY SGERT I DDIM LAWR YN IAWN YN Y CEFN"},
    {"identifier": "sample212", "text": u"DARPARIAETH GOFAL MEITHRIN RHAD AC AM DDIM"},
    {"identifier": "sample213", "text": u"MAEN RHAID IDDI FOD YN RHYWBETH MAE POBL EISIAU BOD YN RHAN OHONI"},
    {"identifier": "sample214", "text": u"DARLLEN YR ERTHYGL YN LLAWN MORGAN A SARA YN CHWARAE CUDDIO"},
    {"identifier": "sample215", "text": u"MAE ADRODDIADAU BOD PAWB I LAWR YN DDIOGEL ERBYN HYN"},
    {"identifier": "sample216", "text": u"MAE UN BYWYD AR CHWÂL YN UN BYWYD YN ORMOD"},
    {"identifier": "sample217", "text": u"ROEDD LOT O BOBL YN GWEIDDI AC YN SGRECHIAN"},
    {"identifier": "sample218", "text": u"ROEDD YR EISTEDDFOD YN BWYSIG IAWN I LLOYD GEORGE"},
    {"identifier": "sample219", "text": u"ALLWN NI DDIM EU TRIN FEL UNRHYW BLAID ARALL"},
    {"identifier": "sample220", "text": u"AC MAE GANDDI DRAWSTORIAD O BOBOL YN GWEITHIO IDDI"},
    {"identifier": "sample221", "text": u"NI CHAFODD UNRHYW UN OEDD YN TEITHIO AR Y BWS EU HANAFU"},
    {"identifier": "sample222", "text": u"DOEDD GAN RAN HELAETH O'R BOBLOGAETH DDIM SWYDDI"},
    {"identifier": "sample223", "text": u"ROEDD EI FAM HEFYD YN POENI BOD EI GROEN YN TROI YN FELYN"},
    {"identifier": "sample224", "text": u"FE GAFODD HITHAU EI DANGOS I BLANT MEWN GWAHANOL GANOLFANNAU HEFYD"},
    {"identifier": "sample225", "text": u"BYDD YR ENILLYDD YN CAEL EI GWAHODD I FOD YN AELOD O'R ORSEDD"},
    {"identifier": "sample226", "text": u"ROEDD YN RHAGORI MEWN CHWARAEON ERAILL PAN OEDD YN IAU CYN CANOLBWYNTIO AR BÊL-DROED"},
    {"identifier": "sample227", "text": u"BYDD GAN YR AWDURDOD SWYDDFA YN Y GOGLEDD HEFYD"},
    {"identifier": "sample228", "text": u"GALL PERFFORMIAD DA GANDDYN NHW ELENI GAEL EFFAITH AR GEFNOGAETH Y DDWY BLAID FAWR"},
    {"identifier": "sample229", "text": u"CAFODD EI HETHOL GAN AELODAU YM MIS TACHWEDD"},
    {"identifier": "sample230", "text": u"CAFODD Y CORFF EI DDARGANFOD GER SIOP TESCO YN Y DDINAS DDYDD SUL"},
    {"identifier": "sample231", "text": u"CAFODD Y GWAITH O ADFER Y CYRFF EI GWBLHAU DDYDD MAWRTH"},
    {"identifier": "sample232", "text": u"MAE PEDWAR O BOBOL ERAILL YN DERBYN TRINIAETH"},
    {"identifier": "sample233", "text": u"ROEDD ENGHREIFFTIAU O AELODAU SENEDDOL YN CAEL EU TARGEDU HEFYD"},
    {"identifier": "sample234", "text": u"DWI YN MEDDWL IDDYN NHW RHOI BOB SIAWNS IDDO FE"},
    {"identifier": "sample235", "text": u"ROEDDEN NI EISIAU EU RHOI I BOBL OEDD YN PERFFORMIO"},
    {"identifier": "sample236", "text": u"MI OEDD TEIMLADAU POBL AR Y PRYD YN AMRWD MEDDAI"},
    {"identifier": "sample237", "text": u"ER MAI MEWN GERDDI TAI PREIFAT OEDD Y RHAN FWYAF"},
    {"identifier": "sample238", "text": u"MAE UNRHYW LEFYDD SYDD DDIM YN CAEL EU LLENWI YN CAEL EU HAIL-HYSBYSEBU"},
    {"identifier": "sample239", "text": u"ROEDD Y DIGWYDDIAD AR FFORDD Y GOGLEDD RHWNG BWS A MENYW OEDD YN CERDDED"},
    {"identifier": "sample240", "text": u"BYDD ANGEN YR UN SGILIAU AR BOB SAFLE OND AR RADDFA UWCH"},
    {"identifier": "sample241", "text": u"MAE HEFYD YN EFFEITHIO AR FY HWYLIAU AC AR FY EGNI"},
    {"identifier": "sample242", "text": u"COFIWCH DDWEUD OS YW HYN YN MYND YN DDIFLAS"},
    {"identifier": "sample243", "text": u"EFALLAI NA FYDD Y LLINELLAU FFÔN YN GWEITHIO AM YN HIR ETO"},
    {"identifier": "sample244", "text": u"Y NOD YN Y PEN DRAW YW CEISIO ENNILL Y BENCAMPWRIAETH"},
    {"identifier": "sample245", "text": u"MAE IEITHWEDD CREFYDD YN DOD YN NATURIOL IAWN I FI"},
    {"identifier": "sample246", "text": u"POWYS OEDD YR UNIG FWRDD IECHYD HEB UNRHYW ACHOSION"},
    {"identifier": "sample247", "text": u"Y GRED YW BOD Y BACHGEN AR EI WYLIAU YN YR ARDAL"},
    {"identifier": "sample248", "text": u"Y RHESWM YW'R HINSAWDD ECONOMAIDD A LLAI O DDEFNYDD O'R ADNODD"},
    {"identifier": "sample249", "text": u"LLADDON NHW FE PAN OEDD E DAN AMHEUAETH YN UNIG"},
    {"identifier": "sample250", "text": u"CAFODD Y FFORDD EI CHAU YN DILYN Y DIGWYDDIAD"},
]