#!/usr/bin/env python 
# -*- coding: utf-8 -*-
PROMPTS = [    
    {"identifier": "sample1", "text": u"AC FE GAFODD SÊFF SIOP Y BWCI EI DWYN HEFYD"},
    {"identifier": "sample2", "text": u"EI GWAITH YM MHEIRIANWAITH Y GWASANAETH SIFIL"},
    {"identifier": "sample3", "text": u"AR DROTHWY UWCH-GYNHADLEDD YR UNDEB EWROPEAIDD"},
    {"identifier": "sample4", "text": u"DIM OND TRI LLE ARALL FELLY I'W RANNU RHWNG Y GWEDDILL"},
    {"identifier": "sample5", "text": u"A DEWCH YN ÔL ATON NI O WYTH O'R GLOCH YN Y BORE, FORE LLUN"},
    {"identifier": "sample6", "text": u"MAE BANER Y DDRAIG GOCH YN CHWIFIO UWCHBEN RHIF DEG HEFYD"},
    {"identifier": "sample7", "text": u"SUL LLAWN BENDITH WRTH ADDOLI DUW EIN CREAWDWR YNG NGHWMNI EIN GILYDD"},
    {"identifier": "sample8", "text": u"FE FYDD Y GWAITH O ROI WYNEB NEWYDD AR FFORDD YR WYDDGRUG YN DECHRAU DYDD SUL"},
    {"identifier": "sample9", "text": u"BU AELODAU PRESENNOL O'R POST BRENHINOL"},
    {"identifier": "sample10", "text": u"DOES NEB YN COGINIO AR FAES STEDDFOD HEBLAW TIPYN O GIG MOCH AC O BOSIB SOSEJ NEU DDWY YN Y BORE"},
    {"identifier": "sample11", "text": u"GAN ADAEL I REW FFURFIO AR FFYRDD SYDD HEB EU GRAEANU"},
    {"identifier": "sample12", "text": u"AC FE FYDD MEWN GRYM O WYTH O'R GLOCH YN NOS, NOS IAU"},
    {"identifier": "sample23", "text": u"TROSGLWYDDO SAFLEOEDD TREFTADAETH A THOILEDAU I FUDIADAU ERAILL"},
    {"identifier": "sample24", "text": u"MAE OEDI CYN TRINIAETHAU YN DIFETHA ANSAWDD BYWYD POBL"},
    {"identifier": "sample25", "text": u"CAFODD Y CRIW EU GALW O ORSAF PEN-Y-BONT AR OGWR I SARN TUA CHWARTER I DDEG O'R GLOCH YN NOS, DDYDD GWENER"},
    {"identifier": "sample26", "text": u"TROI SWYDDFEYDD YN GANOLFAN MEDDYG TEULU?"},
    {"identifier": "sample27", "text": u"FE BARHAWN I FRWYDRO YN URDDASOL AC YN BARCHUS AC YN BOSITIF"},
    {"identifier": "sample28", "text": u"CAFODD DAU GANT UN DEG SAITH O BOBOL EU HARESTIO YM MHRIFDDINAS YR UNOL DALEITHIAU DDOE WRTH I SIOPAU GAEL EU DINISTRIO A CHEIR EU RHOI AR DÂN"},
    {"identifier": "sample29", "text": u"A DARLUN WYDR O DŴR Y JIWBILÎ AR FOEL FAMAU AR EI PHEN"},
    {"identifier": "sample30", "text": u"DADORCHUDDIO PLAC YM MHENTREF RHOSCROWDDER"},
    {"identifier": "sample31", "text": u"MAWRTH UN DEG CHWECH, HANNER AWR WEDI DEUDDEG O'R GLOCH, YN Y BORE"},
    {"identifier": "sample32", "text": u"HANNER AWR WEDI WYTH O'R GLOCH, YN NOS, NOS FERCHER, IONWAR DAU DDEG WYTH"},
    {"identifier": "sample33", "text": u"UCHAFBWYNT Y DYDD AR LWYFAN EISTEDDFOD YR URDD CAERFFILI HEDDIW OEDD Y CADEIRIO"},
    {"identifier": "sample34", "text": u"FU FARW YN SIR BENFRO YN DWY FIL UN DEG UN"},
    {"identifier": "sample35", "text": u"BYDD ANGEN YR UN SGILIAU AR BOB SAFLE OND AR RADDFA UWCH"},
    {"identifier": "sample36", "text": u"Y DYN YN CEISIO ACHUB Y DDWY AETH I DRAFFERTHION YN NHYWYN DDOE"},
    {"identifier": "sample37", "text": u"DDEUDDYDD AR ÔL I'W THEULU FYND AT YR HEDDLU I DDWEUD EI BOD AR GOLL"},
    {"identifier": "sample38", "text": u"EISTEDD AR LIN FY EWYTHR AR SETL YN Y GEGIN"},
    {"identifier": "sample39", "text": u"AMCANION Y FFORDD OSGOI YW LLEIHAU AMSERAU TEITHIO"},
    {"identifier": "sample40", "text": u"ROEDD Y DIGWYDDIAD AR FFORDD Y GOGLEDD RHWNG BWS A MENYW OEDD YN CERDDED"},
    {"identifier": "sample41", "text": u"AR GOLL AR EBRILL SEITHFED, DDAU DDIWRNOD CYN EI BEN-BLWYDD YN DAU DDEG NAW OED"},
    {"identifier": "sample42", "text": u"OLEW COGINIO YN RHWYSTRO DRAENIAU CAERDYDD"},
    {"identifier": "sample43", "text": u"MAE SWYDDOGION TSIEINA BOB AMSER YN PROTESTIO"},
    {"identifier": "sample44", "text": u"GAN MAI IONAWR DAU DDEG PUMP YW DYDD SANTES DWYNWEN"},
    {"identifier": "sample45", "text": u"YR AMSER PERFFAITH I DDIANC AM WYLIAU I DDE EWROP"},
    {"identifier": "sample46", "text": u"RHYWBRYD RHWNG HANNER NOS A PUMP O'R GLOCH Y BORE"},
    {"identifier": "sample47", "text": u"CAFODD NAW AELOD O'R GANG EU CARCHARU GAN FARNWR DDYDD IAU."},
    {"identifier": "sample48", "text": u"NOW AC ELIN A HEFYD POSAU A THASGAU I BLANT"},
    {"identifier": "sample49", "text": u"SYDD BEDWAR PWYNT UWCHBEN Y SAFLEOEDD DISGYN"},
    {"identifier": "sample50", "text": u"DOEDD DIM MODD RHOI BWYDYDD MEWN OERGELL NEU REWGELL"},
    {"identifier": "sample51", "text": u"RHAGFYR UN DEG WYTH, DWY FIL UN DEG UN, HANNER AWR WEDI NAW O'R GLOCH, YN Y BORE"},
    {"identifier": "sample52", "text": u"RHWNG CHWECH O'R GLOCH YN Y BORE DDYDD SADWRN A CHWECH O'R GLOCH YN Y BORE FORE SUL."},
    {"identifier": "sample53", "text": u"EU SIAWNS GORAU O LWYDDIANT YW SEDD CANOL CAERDYDD"},
    {"identifier": "sample54", "text": u"TACHWEDD TRI, DWY FIL A NAW, DEUNAW MUNUD I DDEG O'R GLOCH, YN Y BORE"},
    {"identifier": "sample55", "text": u"TRA BOD PAWB AM OSOD EU STAMP EU HUNAIN AR Y CHWARAE"},
    {"identifier": "sample56", "text": u"OND GAN FOD EI RIENI YN CADW GAREJ LLANPUMSAINT"},
    {"identifier": "sample57", "text": u"AI BATIWR NEU FOWLIWR FYDD Y CHWARAEWR NEWYDD HWNNW"},
    {"identifier": "sample58", "text": u"CAFODD DROS DAU GANT O GYRFF EU HEPGOR O'R SAFONAU IAITH"},
    {"identifier": "sample59", "text": u"ER NAD OEDD GEN I UNRHYW AWYDD I FOD MEWN GRŴP FY HUN"},
    {"identifier": "sample60", "text": u"GWELL MWYNHAU YM MANGOR NA CHWERWI YNG NGHAERGRAWNT"},
    {"identifier": "sample61", "text": u"MAI TRI DEG UN, DWY FIL A DDEG, SAITH MUNUD AR HUGAIN WEDI DEUDDEG O'R GLOCH, YN Y BORE"},
    {"identifier": "sample62", "text": u"Y NOD YN Y PEN DRAW YW CEISIO ENNILL Y BENCAMPWRIAETH"},
    {"identifier": "sample63", "text": u"NIWL RHEWLLYD YN ACHOSI OEDI YN Y DE"},
    {"identifier": "sample64", "text": u"BYDD UNIGOLION YN PARHAU I ALLU DATGAN EU PARODRWYDD I ROI EU HORGANAU DRWY ROI EU HENW AR RESTR"},
    {"identifier": "sample65", "text": u"NOS FERCHER HANNER AWR I UN AR DDEG O'R GLOCH, YN NOS"},
    {"identifier": "sample66", "text": u"ERBYN MIL NAW CHWE DEG PUMP, ROEDD PENTREF CAPEL CELYN O DAN DDŴR"},
    {"identifier": "sample67", "text": u"MAE MORLO IACH YN FAWR AC YN DEW AC HEB WDDF"},
    {"identifier": "sample68", "text": u"CAFODD OSIAN ROBERTS EI FAGU YM MODFFORDD"},
    {"identifier": "sample69", "text": u"BETH YW BARN CERI AM Y PROFION DADLEUOL"},
    {"identifier": "sample70", "text": u"MAE AWDURDOD RHEILFFYRDD CENEDLAETHOL FFRAINC"},
    {"identifier": "sample71", "text": u"RHAGLEN Y BYD AR BEDWAR YN MYND AR ÔL TOWTIAID"},
    {"identifier": "sample73", "text": u"MAE GAN YR ELYRCH DDIGON I GNOI CIL AMDANO FELLY,"},
    {"identifier": "sample74", "text": u"OND OS OES ANGEN RHYWBETH ARNOM NI AR LEFEL UWCH"},
    {"identifier": "sample75", "text": u"AC FE ALL Y CYRFF HYN GODI TÂL AM Y GWASANAETH"},
    {"identifier": "sample76", "text": u"A NHW OEDD YN ARWAIN Y SGÂM YN ÔL HEDDLU GWENT."},
    {"identifier": "sample77", "text": u"PERFFORMIADAU CLODWIW MEWN DAU GWPAN BYD"},
    {"identifier": "sample78", "text": u"GAN ANELU AM BARC MANWERTHU PARC LECWYDD"},
    {"identifier": "sample79", "text": u"PA MOR AMERICANAIDD YW DIGON AMERICANAIDD?"},
    {"identifier": "sample80", "text": u"DOES DIM AMHEUAETH BOD YR ALBAN YN SIOMEDIG IAWN AR ÔL PERFFORMIAD DIFFLACH YN EU GÊM AGORIADOL NHW"},
    {"identifier": "sample81", "text": u"OEDD YN DAU DDEG SAITH, I FARWOLAETH YN EI FFLAT YN HWLFFORDD"},
    {"identifier": "sample82", "text": u"BETH YW'R PROSIECT MWYAF I TI FOD YN RHAN OHONO"},
    {"identifier": "sample83", "text": u"NAWR Y CWBL SYDD GANDDYN NHW YW TWMPATH O RWBEL"},
    {"identifier": "sample84", "text": u"OS EWCH I'W GWELD MEWN ARDAL SYDD Â CHWAETH DDA MEWN MIWSIG"},
    {"identifier": "sample85", "text": u"MAE GWION O FENLLECH YN RHANNU RHAN LLEW EFO IFAN PRITCHARD"},
    {"identifier": "sample86", "text": u"MAE CASNEWYDD YN CODI I SAFLE UN DEG NAW YN Y TABL"},
    {"identifier": "sample87", "text": u"DOES GANDDYN NHW WRTH GWRS DDIM Y FANTAIS O FYW YN Y SIR"},
    {"identifier": "sample88", "text": u"ROEDD ANTURIAETHAU JINI MÊ YN DILYN HYNT A HELYNT Y FERCH FACH DDIREIDUS O'R UN ENW"},
    {"identifier": "sample89", "text": u"ER Y GELLIR DISGWYL I HELEN MARY JONES ENNILL LLANELLI,"},
    {"identifier": "sample90", "text": u"AC FE GAFODD GWASANAETH TÂN AC ACHUB Y DE EU GALW I DDAU DDIGWYDDIAD,"},
    {"identifier": "sample91", "text": u"FEL EU BOD YN MEDRU RHANNU EU PROBLEMAU NHW"},
    {"identifier": "sample92", "text": u"DYW E DDIM YN AMLWG BETH YW NEU OEDD PWRPAS Y STRWYTHURAU"},
    {"identifier": "sample93", "text": u"DARGANFUWYD FOD GANDDO GRAC YN EI BENGLOG"},
    {"identifier": "sample94", "text": u"WRTH I CHWE SWYDD UWCH REOLI GAU AC I DAIR SWYDD NEWYDD GAEL EU CREU"},
    {"identifier": "sample95", "text": u"TÂN YN ACHOSI I DO SIOP DDODREFN DDISGYN YNG NGHAERDYDD"},
    {"identifier": "sample96", "text": u"GAN ROI ETHOLIAD DWY FIL UN DEG UN FEL ENGHRAIFFT"},
    {"identifier": "sample97", "text": u"OS YW PLAID YN LLWYDDO I'W ESBONIO YN DDIGONOL"},
    {"identifier": "sample98", "text": u"YN DILYN DADL DEULUOL YN EI GARTREF YN LLAWHADEN."},
    {"identifier": "sample99", "text": u"NOS SADWRN BYDD DAU GANT CHWE DEG O GYN-CHWARAEWYR"},
    {"identifier": "sample100", "text": u"OND FE DDECHREUON NHW SETLO YNG NGHAERDYDD A MWYNHAU BOD MOR AGOS I'W WYRION"},
    {"identifier": "sample101", "text": u"CAFODD HOLL DRENAU I MEWN AG ALLAN O'R ORSAF EU GOHIRIO HYD AT HANNER AWR WEDI WYTH"},
    {"identifier": "sample102", "text": u"MORGANNWG AR Y BLAEN O UN DEG NAW RHEDIAD"},
    {"identifier": "sample103", "text": u"POSIBILIADAU DAMCANIAETHOL YW RHAIN AR HYN O BRYD"},
    {"identifier": "sample104", "text": u"MAE GORSAF HEOL Y FRENHINES AR GAU ERS CHWARTER I SAITH"},
    {"identifier": "sample105", "text": u"AWSTRIA A LWCSEMBWRG CYN GORFOD WYNEBU IWGOSLAFIA YN Y ROWND HONNO"},
    {"identifier": "sample106", "text": u"PAM NAD YW MARTIN YN TEIMLO UNRHYW FATH O EDIFEIRWCH"},
    {"identifier": "sample107", "text": u"CAFODD ELFENNAU O FLWYDDYN ANTUR DWY FIL UN DEG CHWECH EU BEIRNIADU YM MIS MEDI"},
    {"identifier": "sample108", "text": u"BUDDUGOLIAETH I FOIS Y SOSBAN MEWN GÊM AGOS"},
    {"identifier": "sample109", "text": u"AC MAE WYTHFED DYN YN CAEL EI HOLI YN Y DDALFA"},
    {"identifier": "sample110", "text": u"EI FOD EISIAU OSGOI UNRHYW BROBLEMAU TRAFFIG POSIB"},
    {"identifier": "sample111", "text": u"OND FOD YR AD-DREFNU MEWNOL DAL YN MYND RHAGDDI"},
    {"identifier": "sample112", "text": u"CAFODD Y GWASANAETHAU BRYS EU GALW TOC AR ÔL CHWECH O'R GLOCH"},
    {"identifier": "sample113", "text": u"ER MWYN CEISIO DENU MWY O FERCHED A PHOBOL O LEIAFRIFOEDD ETHNIG I'W RHENGOEDD"},
    {"identifier": "sample114", "text": u"CYN I REWLIFOEDD MAWR GOGLEDD AMERICA DDADMER"},
    {"identifier": "sample115", "text": u"METHIANT I GAEL GWERTH AM ARIAN MEWN PROSES CAFFAELIAID"},
    {"identifier": "sample116", "text": u"MAE COLLI GWASANAETHAU MEDDYG TEULU A GWASANAETH BWS MEWN AMSER BYR YN HER FAWR I NIFER O BOBL YNG NGHOELBREN"},
    {"identifier": "sample117", "text": u"AR ÔL DISGYN I LAWR SIAFFT LIFFT YM MHONTCANNA"},
    {"identifier": "sample118", "text": u"YN ÔL DAFYDD ROBERTS O GWMNI RECORDIAU SAIN"},
    {"identifier": "sample119", "text": u"TROI SIED NWYDDAU YN GANOLFAN CREADIGOL"},
    {"identifier": "sample120", "text": u"PRIF SEREN RWSIA I FETHU EWRO DWY FIL UN DEG CHWECH"},
    {"identifier": "sample121", "text": u"OEDD YN ADLEISIO RÔL BRENGAIN Y LLAWFORWYN YN Y CHWEDL"},
    {"identifier": "sample122", "text": u"OND Y BROBLEM YW EU BOD YN ANODD DOD O HYD IDDYNT"},
    {"identifier": "sample123", "text": u"EFALLAI EU BOD NHW EISOES YN PARATOI AM SENEDD GROG"},
    {"identifier": "sample124", "text": u"OND OS SIARADWCH CHI AG AELODAU CEIDWADOL OEDD AM AROS"},
    {"identifier": "sample125", "text": u"Y BYDD Y GWEINIDOG YN GWRTH-DROI'R TORIADAU HYN"},
    {"identifier": "sample126", "text": u"MAE SIOP BODLON HEFYD YN RHAN O'R FENTER"},
    {"identifier": "sample127", "text": u"DARGANFOD FFLIW ADAR MEWN HAID O IEIR A HWYAID YN SIR GÂR"},
    {"identifier": "sample128", "text": u"FE GEISIODD HI SIARAD AG E ER MWYN OSGOI EI WYLLTIO"},
    {"identifier": "sample129", "text": u"DRAIG LLANRHAEADR-YM-MOCHNANT A PHISTYLL RHAEADR"},
    {"identifier": "sample130", "text": u"OND FI OEDD YR UNIG UN YN FY NHEULU OEDD YN GALLU SIARAD YR IAITH"},
    {"identifier": "sample131", "text": u"BYDD Y LLANW AR EI UCHAF RHWNG NOS SUL A BORE LLUN"},
    {"identifier": "sample132", "text": u"A HEB SAITH NEU WYTH SYDD HEB CHWARAE YN Y GEMAU GRŴP RHAGBROFOL."},
    {"identifier": "sample133", "text": u"NI CHAFODD NEB ANAF PAN DDAETH COEDEN I LAWR AR Y BRIFF FFORDD DRWY BORTHAETHWY"},
    {"identifier": "sample134", "text": u"OEDD YN CAEL EI ADNABOD FEL Y FELLTEN GOCH OHERWYDD LLIW EI LIFRAU RASIO"},
    {"identifier": "sample135", "text": u"RHAI WRTH GERDDED AR DRAWS EHANGDER TRAETH LAFAN AR LANW ISEL."},
    {"identifier": "sample136", "text": u"ELENI YW BLWYDDYN OLAF YR ARCHDDERWYDD WRTH Y LLYW,"},
    {"identifier": "sample137", "text": u"Y MAE CARIAD MAWR TUAG ATO AC Y MAE POBL YM MHEDWAR BAN BYD YN DRIW IAWN IDDO O HYD"},
    {"identifier": "sample138", "text": u"PI-PI YN FY NHROWSUS MEWN CWCH RHWYFO YNG NGLAN-LLYN"},
    {"identifier": "sample139", "text": u"OND NID OEDD YN GALLU GWELD UNRHYW FFILM O'R DIGWYDDIAD"},
    {"identifier": "sample140", "text": u"FFRWYTHAU A PHROTEIN ER MWYN GWELLA EI DDEIET"},
    {"identifier": "sample141", "text": u"RHOI MWY O GEFNOGAETH I GLEIFION TRWY HOLL HYNT EU CLEFYD"},
    {"identifier": "sample142", "text": u"A PHAWB RHYWSUT FEL EU BOD YN OSGOI DATRYS UNRHYW BROBLEM"},
    {"identifier": "sample143", "text": u"FE FWYNHEAIS GLAN-LLYN A LLANGRANNOG FEL EI GILYDD"},
    {"identifier": "sample144", "text": u"MEDALAU EISTEDDFOD I DAN PUW A DERI TOMOS"},
    {"identifier": "sample145", "text": u"PWY YW'R BACHGEN AR GEFN EI FRAWD YN Y CARDIGAN LIWGAR"},
    {"identifier": "sample146", "text": u"ER MWYN GADAEL BLODAU A SLOGANAU NATSIAIDD."},
    {"identifier": "sample147", "text": u"MAE GENNYM DDAU AELOD O STAFF LLAWN AMSER A THRI AELOD RHAN-AMSER"},
    {"identifier": "sample148", "text": u"CASNEWYDD YN DATHLU WRTH AROS YN ADRAN DAU"},
    {"identifier": "sample149", "text": u"NOD BLWYDDYN ANTUR DWY FIL UN DEG CHWECH YW"},
    {"identifier": "sample150", "text": u"DIGWYDDODD Y LLADRAD MEWN SIOP YNG NGHWMBRÂN"},
    {"identifier": "sample151", "text": u"A BOD HYN YN EU PROCIO NHW I SIARAD AM Y THEMÂU"},
    {"identifier": "sample152", "text": u"OS SAETHWCH CHI TRI DEG GWAITH FE GEWCH CHI DAIR GÔL"},
    {"identifier": "sample153", "text": u"OND FI OEDD YR UN MWYAF DIBROFIAD O BELL FFORDD"},
    {"identifier": "sample154", "text": u"NEU WRTH IDDYN NHW CAEL EU SATHRU GAN RHYW BROP MAWR"},
    {"identifier": "sample155", "text": u"MORGANNWG AR DROTHWY EU PUMED BUDDUGOLIAETH O'R BRON YN Y BENCAMPWRIAETH"},
    {"identifier": "sample156", "text": u"O GELC O FODRWYAU A CHEINIOGAU RHUFEINIG O SILI"},
    {"identifier": "sample157", "text": u"MWY YN GOFYN AM HELP I'W HATAL RHAG MYND YN DDIGARTREF"},
    {"identifier": "sample158", "text": u"MAE LLWYBR YN FWY CUL AC YN FWY SERTH WRTH GODI UWCHBEN LLYN GLASLYN"},
    {"identifier": "sample159", "text": u"BYDD Y FFORDD AR GAU RHWNG WYTH O'R GLOCH NOS SADWRN A CHWECH O'R GLOCH FORE LLUN"},
    {"identifier": "sample160", "text": u"NES Y BYDD AML I FFOLOG YN GLAIS A CHREITHIAU AR HYD EI HOES"},
    {"identifier": "sample161", "text": u"FE FYDD RHODRI TALFAN DAVIES A MERI HUWS YN CWRDD EI CHAIS HI"},
    {"identifier": "sample162", "text": u"FE YW'R BATIWR GORAU GAFODD MORGANNWG ERIOED"},
    {"identifier": "sample163", "text": u"MILOEDD YN DATHLU HIRDDYDD HAF YNG NGHÔR Y CEWRI"},
    {"identifier": "sample164", "text": u"RHEOLWR GWEITHREDIADAU Y BAD ACHUB YNG NGHRICCIETH"},
    {"identifier": "sample165", "text": u"TROWCH YN DDIGALON AT EICH FFRIND NEWYDD A DWEUD"},
    {"identifier": "sample166", "text": u"AC FE LWYDDODD Y DDAU I DDIANC A CHUDDIO MEWN COEDWIG AM ORIAU HIR MEWN AMODAU RHEWLLYD"},
    {"identifier": "sample167", "text": u"BELLACH MAE HI WRTH EI BODD YNG NGHANOL BWRLWM PUMP O WYRION A DWY WYRES"},
    {"identifier": "sample168", "text": u"GAN FOD CRAEN CHWE DEG TUNNELL YN RHWYSTRO UN LÔN O DAIR TUA HANNER FFORDD LAN Y RHIW"},
    {"identifier": "sample169", "text": u"LLUNIAU O FAES EISTEDDFOD YR URDD SIR BENFRO DWY FIL UN DEG TRI YNG NGHILWENDEG GER BONCATH"},
    {"identifier": "sample170", "text": u"A BOD YR ARIAN HEFYD YN EFFEITHIO AR EU HAWCH"},
    {"identifier": "sample171", "text": u"AMSER AM LECHEN LÂN YNG NGHASTELL PENRHYN?"},
    {"identifier": "sample172", "text": u"O, FE ALLWCH CHI FOD YN BLANCTON MAWR A PHWYSIG"},
    {"identifier": "sample173", "text": u"MAE RHAI O'R RHEINY OEDD YN DATHLU YN Y DDINAS NEITHIWR"},
    {"identifier": "sample174", "text": u"PA RINWEDDAU SYDD GANDDO FE FEL ARWEINYDD?"},
    {"identifier": "sample175", "text": u"SEF GWAHARDDIAD AR LEFYDD PENODOL FEL SIOPAU"},
    {"identifier": "sample176", "text": u"BYDD FFLUR DAFYDD YN CYD-GYNHYRCHU'R FFILM AG EUROS LYN,"},
    {"identifier": "sample177", "text": u"EFALLAI COLLI FY MAM-GU A FY NHAD-CU YW'R FFACTOR FWYA"},
    {"identifier": "sample178", "text": u"FFOADURIAID AR BEN TOEON YN PROTESTIO"},
    {"identifier": "sample179", "text": u"TREULIO DWY AWR Y DYDD YN POSTIO NEGESEUON"},
]
