
#!/usr/bin/env python 
# #encoding: UTF-8 
PROMPTS = [    
    {"identifier": "sample1", "text": u"EFYDD OEDD Y RHAN FWYAF OND ROEDD TRI O HAEARN CLEDDYF PEN GWAYWFFON A CHRYMAN"},
    {"identifier": "sample2", "text": u"DIM OND UN PERSON A GAIFF SIARAD AR Y TRO"},
    {"identifier": "sample3", "text": u"MAE UWCHGYNADLEDDAU O FEWN EWROP YN FAES GWAHANOL"},
    {"identifier": "sample4", "text": u"MAE ANGEN FELLY DDARPARU TAI I'W PRYNU NEU I'W RHENTU YN YR ARDALOEDD HYN"},
    {"identifier": "sample5", "text": u"GWN NAD YDYCH BYTH YN RHOI WLTIMATA IMI PETER"},
    {"identifier": "sample6", "text": u"FELLY NID OES OTS YM MHA FFORDD YR EDRYCHWN AR HYN"},
    {"identifier": "sample7", "text": u"YM MOSCOW FE DDATBLYGODD DDIDDORDEB MAWR MEWN LLENYDDIAETH FARCSAIDD AC YMUNODD"},
    {"identifier": "sample8", "text": u"Y PRIF NWYDDAU A FASNACHWYD OEDD CAETHWEISION AUR IFORI A SBEISIAU"},
    {"identifier": "sample9", "text": u"YR WYF YN SIWR Y GALL JANE ROI MANYLION ICHI OS DYMUNWCH"},
    {"identifier": "sample10", "text": u"NI ALLWN SEFYLL UWCH BEN Y CWANGOS WRTH IDDYNT ARWYDDO SIECIAU"},
    {"identifier": "sample11", "text": u"LLWYDDODD Y POLISI HWN PAN GYFLWYNWYD EF LEDLED DINAS GLASGOW"},
    {"identifier": "sample12", "text": u"A FYDD GLINIADURON AR GAEL YNO NEU OES RHAID DOD AG UN GYDA NI"},
    {"identifier": "sample13", "text": u"NI ALLWN ORFODI AWDURDOD I DDERBYN CYMORTH YN GROES I'W EWYLLYS"},
    {"identifier": "sample14", "text": u"MAENT YN GYFRIFOL AM SIAPIO A MOWLDIO DINASYDDION Y GENHEDLAETH NESAF"},
    {"identifier": "sample15", "text": u"DDOE CEFAIS Y PLESER O FOD YNG NGHINIO FFURFIOL ADRODDIAD GWEINI"},
    {"identifier": "sample16", "text": u"YR WYF YN SIWR BOD BUSH YN CREDU EI FOD YN CHWARAE RHAN Y SIRYF MEWN FFILM GOWBOIS"},
    {"identifier": "sample17", "text": u"MAE ANGEN HELP AR EIN HAWDURDODAU LLEOL I HELPU POBL MEGIS HUW TUDOR"},
    {"identifier": "sample18", "text": u"GOBEITHIAF MAI AUR DILIN YW DISTAWRWYDD AC Y CAIFF YR ANGHYDFOD EI DDATRYS"},
    {"identifier": "sample19", "text": u"SERCH HYNNY NI WN A GEWCH FADDEUANT BYTH GAN GYFIEITHYDD DIRPRWY ARLYWYDD TSIEINA"},
    {"identifier": "sample20", "text": u"Y LLYWYDD CYFEIRIASOCH AT YMGAIS DDOE I GODI PWYNT O DREFN AR Y MATER HWN"},
    {"identifier": "sample21", "text": u"MAE TRI O'R SAFLEOEDD ERAILL YM MERTHYR DAU AR YR UN SAFLE AC UN ARALL YN NOWLAIS"},
    {"identifier": "sample22", "text": u"YNGHYLCH THERAPYDDION MAE CYSYLLTIAD RHWNG Y GWASANAETHAU IECHYD AC ADDYSG"},
    {"identifier": "sample23", "text": u"BYDDAI TSAR CANSER YN GYFAILL DEFNYDDIOL ICHI"},
    {"identifier": "sample24", "text": u"RHAID INNI YNG NGHYMRU FOD YN FODLON AR Y BRIWSION ODDI AR FWRDD SAN STEFFAN"},
    {"identifier": "sample25", "text": u"FEL Y MAE NATUR EICH CWESTIWN YN DANGOS NI ALLWN GYFLAWNI HYN DRWY EI EWYLLYSIO YN UNIG"},
    {"identifier": "sample26", "text": u"NID OLEW YW'R UNIG RESWM DROS Y RHYFEL HWN"},
    {"identifier": "sample27", "text": u"PETER LAW SIARADAF AM HYNNY YMHEN EILIAD"},
    {"identifier": "sample28", "text": u"NI DDYLAI GWASANAETH CYHOEDDUS O'R FATH DDIBYNNU AR ARWERTHIANNAU CIST CAR A BOREAU COFFI"},
    {"identifier": "sample29", "text": u"WRTH GWRS PROSES DDYSGU YW HON OND MAE GENNYF AWGRYM I ANDREW ERBYN Y FLWYDDYN NESAF"},
    {"identifier": "sample30", "text": u"BOED I DDUW FENDITHIO EICH TRAFODAETHAU YN Y MISOEDD A DDAW"},
    {"identifier": "sample31", "text": u"ROEDD DROS EU HANNER YN DDYNION RHYS AP THOMAS"},
    {"identifier": "sample32", "text": u"EFALLAI EICH BOD CHI MEWN TROWSUS BYR; OND NID OEDDWN I"},
    {"identifier": "sample33", "text": u"CAIFF LLAETH TESCO EI BECYNNU YN BIRMINGHAM"},
    {"identifier": "sample34", "text": u"OS OES BLE MAE NHW AC OS DDIM SUT MAE MYND O GWMPAS EU CREU"},
    {"identifier": "sample35", "text": u"PLANNWYD CNYDAU OND METHODD Y CYNHAEAF OHERWYDD DIFFYG GLAW"},
    {"identifier": "sample36", "text": u"NID OEDD ANGEN INNI ADAEL YNYSHIR GAN FOD POB SIOP YNO"},
    {"identifier": "sample37", "text": u"FODD BYNNAG RHAID INNI GOFIO BOD ERAILL YNGHUDD"},
    {"identifier": "sample38", "text": u"JYST Y CWESTIWN O LYTHYREN FAWR NEU BACH OEDD YN FY NRYSU"},
    {"identifier": "sample39", "text": u"EFALLAI Y CAFODD EI CHOMISIYNU GAN GEORGE BUSH"},
    {"identifier": "sample40", "text": u"GWELAIS Y GEFNOGAETH ARUTHROL YR OEDDENT YN EI RHOI I'W GILYDD"},
    {"identifier": "sample41", "text": u"Y CYNLLUN CYMORTH PROSESU LLOI YW'R BROBLEM ARALL SYDD GENNYM"},
    {"identifier": "sample42", "text": u"RWYF AM DDILEU Y DDOLEN EMYN YN YR ERTHYGL AM JOSEPH PARRY"},
    {"identifier": "sample43", "text": u"FELLY ONID SIOE CYN YR ETHOLIAD YW'R CYFAN OLL"},
    {"identifier": "sample44", "text": u"BETH FYDD YN DIGWYDD I'W CEISIADAU NHW YN YSTOD Y CYFNOD PONTIO"},
    {"identifier": "sample45", "text": u"MAE PRYDER YNGHYLCH Y DIFFYG CYFATHREBU RHWNG STAFF UWCH AC ERAILL"},
    {"identifier": "sample46", "text": u"ILDIAF I'W WYBODAETH GYFREITHIOL RAGORACH"},
    {"identifier": "sample47", "text": u"GWRTHODODD NICK BROWN DDOE YMRWYMO I IAWNDAL EANG"},
    {"identifier": "sample48", "text": u"PETER LAW AI DULL GWEITHREDU CORFFORAETHOL GAN DAVIES A DAVIES YW HWN"},
    {"identifier": "sample49", "text": u"PAN OEDDWN YN FACHGEN YR OEDD GENNYM LETYWR"},
    {"identifier": "sample50", "text": u"MAENT YN FFOI RHAG TRAIS AC ARSWYD RHYFEL HAINT A PHLA"},
    {"identifier": "sample51", "text": u"CADER YMADRODD AREITHFA; CADER BUWCH PWRS BUWCH"},
    {"identifier": "sample52", "text": u"YN YR UN MODD MYNEGODD FFEDERASIWN CYNGHORAU IECHYD CYMUNED CONWY EI"},
    {"identifier": "sample53", "text": u"CHWARAE YW HYFFORDDIANT NATUR AR GYFER BYWYD"},
    {"identifier": "sample54", "text": u"OS OES UNRHYW WRTHWYNEBIADAU POSTIWCH NHW FAN HYN"},
    {"identifier": "sample55", "text": u"AIL BROBLEM YW CYRCHU AT THERAPYDDION LLEFERYDD DRWY GYFRWNG Y GYMRAEG"},
    {"identifier": "sample56", "text": u"MEWN GAIR ROEDD TYWYSOGAETH CYMRU I FFURFIO UN ENDID FFIWDAL"},
    {"identifier": "sample57", "text": u"CEIR HYD I RIBOSOMAU EWCARYOTIG MEWN DAU LEOLIAD"},
    {"identifier": "sample58", "text": u"MAENT YN DAL I FOD YN SOWND YN YR HEN FFYRDD O EDRYCH AR DDARPARU ADDYSG"},
    {"identifier": "sample59", "text": u"MAE EWROP EISOES YN CYNNIG ANOGAETHAU I BOBL IFANC FFERMIO"},
    {"identifier": "sample60", "text": u"YMLADDODD CENHEDLAETH FY NHAID YN Y FFOSYDD YN FFRAINC"},
    {"identifier": "sample61", "text": u"GOBEITHIAF Y BYDD Y CYRFF CHWARAEON HEFYD YN CYDNABOD PWYSIGRWYDD CHWARAEON"},
    {"identifier": "sample62", "text": u"DANGOSODD HEFYD MAI EWROP YW PRIF BARTNER MASNACHU PRYDAIN A DYMA LLE Y MAE EIN DYFODOL"},
    {"identifier": "sample63", "text": u"MAE POBL YN EI PHARCHU AM MAI NHW SYDD YN BERCHEN ARNI"},
    {"identifier": "sample64", "text": u"ATEGAF HYNNY GAN NODI CYFRANIAD Y SIOEAU"},
    {"identifier": "sample65", "text": u"YN NE EWROP NI ODDEFIR I BOBL O BA OEDRAN BYNNAG GERDDED Y STRYDOEDD YN FEDDW"},
    {"identifier": "sample66", "text": u"YR OEDD SGITSOFFRENIA AR FAB IFANC Y TEULU"},
    {"identifier": "sample67", "text": u"YN FY NHYB I BYDD TAIR EFFAITH YN DEILLIO O'R TORIADAU HYN"},
    {"identifier": "sample68", "text": u"GYDA MAP PENDANT A THERFYNOL NI DDYLAI UNRHYW ANGHYDFOD FYND DROS BEN LLESTRI"},
    {"identifier": "sample69", "text": u"AM GWESTIWN TROELLOG HYD YN OED GENNYCH CHI NICK"},
    {"identifier": "sample70", "text": u"TREULIODD JONES EI OES I GEISIO DYFNHAU; YMWYBYDDIAETH GENEDLAETHOL YMHLITH Y CYMRY"},
    {"identifier": "sample71", "text": u"RHODDWYD COPI IMI GAN JEFF JONES YN LLIW LLACHAR Y DEMOCRATIAID RHYDDFRYDOL"},
    {"identifier": "sample72", "text": u"YMDDENGYS MAE EIN CYFRIFOLDEB NI YN AWR YW DANGOS EIN HEWYLLYS DA FEL CYNULLIAD"},
    {"identifier": "sample73", "text": u"MAE CYSYLLTIAD RHWNG CHWARAEON A THWRISTIAETH"},
    {"identifier": "sample74", "text": u"EISTEDDWCH NEU EWCH O'R SIAMBR OS GWELWCH YN DDA"},
    {"identifier": "sample75", "text": u"MAENT AM FOD YN RHAN O JIG-SO Y DDARPARIAETH IECHYD HON"},
    {"identifier": "sample76", "text": u"LLONGYFARCHAF JANE AR YR YMRWYMIAD HWNNW"},
    {"identifier": "sample77", "text": u"NI CHEWCH DDARLLEN DATGANIADAU A BARATOWYD"},
    {"identifier": "sample78", "text": u"YN ANFFODUS COLLAIS FY NGALLU I GANOLBWYNTIO YCHYDIG PAN DDAETH Y NEWYDDION O AZERBAIJAN"},
    {"identifier": "sample79", "text": u"CEIR YR UN SYNIAD YM MARDDONIAETH GYNNAR YR EINGL-SACSONIAID"},
    {"identifier": "sample80", "text": u"DOES DIM CYSYLLTIAD RHWNG Y BARWNIAETH HYN A BARWN BONHEDDIG"},
    {"identifier": "sample81", "text": u"NID OES GAN Y CYNULLIAD UNRHYW BWERAU I DDARPARU CYMORTH REFENIW UNIONGYRCHOL I YSGOLION"},
    {"identifier": "sample82", "text": u"NID OES OTS FAINT O ARIAN A FUDDSODDWCH YN HYNNY GAN NA ELLID BYTH EI WYRDROI"},
    {"identifier": "sample83", "text": u"YN Y PEN DRAW ARIAN CYHOEDDUS YW HWN AC NI ALLWN ROI SIECIAU GWAG"},
    {"identifier": "sample84", "text": u"YNO YN NGHWM LLYN Y GADAIR ROEDD Y CAWR YN EISTEDD"},
    {"identifier": "sample85", "text": u"CADARNHAWYD YR ACHOS YNG NGAERWEN OND CLIRIWYD Y GWEDDILL"},
    {"identifier": "sample86", "text": u"MAE GAN Y DDAEAR UN LLOEREN NATURIOL Y LLEUAD"},
    {"identifier": "sample87", "text": u"MAE HYNNY YN RHYWBETH IDDO EF CNOI CIL ARNO"},
    {"identifier": "sample88", "text": u"DYLAI EIN HARWEINYDD ALED ROBERTS WYBOD AM Y PETHAU HYN OHERWYDD MAE EF YN DWRNAI"},
    {"identifier": "sample89", "text": u"DYNA UN RHESWM PAM BOD TANWYDD YN PRINHAU MOR GYFLYM"},
    {"identifier": "sample90", "text": u"AI EICH CYMHELLIAD YW OSGOI AILADRODD HYNNY"},
    {"identifier": "sample91", "text": u"YR OEDDWN YN FALCH PAN DDAETH FY MAB YN SGOWT BRWDFRYDIG"},
    {"identifier": "sample92", "text": u"A ALL LLEW SMITH OFYN AM GEFNOGAETH PETER LAW HEDDIW"},
    {"identifier": "sample93", "text": u"A ALLWCH SICRHAU BOD POB PARAGRAFF FFYNHONNELL"},
    {"identifier": "sample94", "text": u"YR WYF YN ARBENNIG O BRYDERUS FODD BYNNAG AM Y PROBLEMAU HIRHOEDLEDD"},
    {"identifier": "sample95", "text": u"A OES GENNYCH UNRHYW GYNLLUNIAU I DDARPARU GWASANAETH OFFTHALMOLEG SYMUDOL"},
    {"identifier": "sample96", "text": u"NAW WFFT LYWYDD I BLAID Y LLIAWS AC NID YR YCHYDIG"},
    {"identifier": "sample97", "text": u"YR OEDD TAIR O'R PLEIDIAU AM GAEL NAW AELOD AC YR OEDDEM NI AM GAEL NIFER ARALL"},
    {"identifier": "sample98", "text": u"SONIODD HUW AM ANGHENION YSGOLION DIFREINTIEDIG"},
    {"identifier": "sample99", "text": u"NID OEDD MODD ADEILADU PUMP O'R CHWE CHYNLLUN O FEWN Y TIR A NEILLTUWYD"},
    {"identifier": "sample100", "text": u"MAE ANGEN HELP CYLLIDOL UNIONGYRCHOL NAWR"},
    {"identifier": "sample101", "text": u"A YDYCH YN YSTYRIED YR OPSIWN DISGOWNT"},
    {"identifier": "sample102", "text": u"CEFFYL DA YW EWYLLYS AC NID OES EWYLLYS NEU NID OES DIGON O EWYLLYS"},
    {"identifier": "sample103", "text": u"CYSIDRWYD LLEOLIAD YNG NGHAINT YN OGYSTAL"},
    {"identifier": "sample104", "text": u"DIM BYD YN YR ERTHYGL HEBLAW UN DAU TRI"},
]